
#ifndef _C1_c_7_
#define _C1_c_7_

#ifdef __cplusplus
extern "C" {
#endif

extern void F7_205(EIF_REFERENCE);
extern void F7_208(EIF_REFERENCE);
extern EIF_INTEGER_32 F7_212(EIF_REFERENCE);
extern EIF_INTEGER_32 F7_213(EIF_REFERENCE);
extern EIF_INTEGER_32 F7_214(EIF_REFERENCE);
extern EIF_INTEGER_32 F7_215(EIF_REFERENCE);
extern void F7_217(EIF_REFERENCE, EIF_POINTER);
extern EIF_INTEGER_32 F7_218(EIF_REFERENCE);
extern EIF_INTEGER_32 F7_219(EIF_REFERENCE);
extern EIF_INTEGER_32 F7_220(EIF_REFERENCE);
extern void F7_221(EIF_REFERENCE, EIF_POINTER, EIF_POINTER);
extern EIF_INTEGER_32 F7_222(EIF_REFERENCE, EIF_POINTER);
extern EIF_POINTER F7_224(EIF_REFERENCE, EIF_POINTER);
extern EIF_POINTER F7_225(EIF_REFERENCE, EIF_POINTER);
extern EIF_INTEGER_32 F7_229(EIF_REFERENCE, EIF_POINTER);
extern EIF_INTEGER_32 F7_230(EIF_REFERENCE, EIF_POINTER);
extern EIF_INTEGER_32 F7_231(EIF_REFERENCE, EIF_POINTER);
extern void EIF_Minit7(void);
extern void F131_1388(EIF_REFERENCE, EIF_POINTER, EIF_INTEGER_32);

#ifdef __cplusplus
}
#endif

#endif
