
#ifndef _C1_en3_
#define _C1_en3_

#ifdef __cplusplus
extern "C" {
#endif

extern void F3_42(EIF_REFERENCE, EIF_REFERENCE);
extern EIF_REFERENCE F3_44(EIF_REFERENCE);
extern EIF_REFERENCE F3_45(EIF_REFERENCE);
extern void F3_48(EIF_REFERENCE, EIF_REFERENCE, EIF_REFERENCE);
extern EIF_BOOLEAN F3_49(EIF_REFERENCE);
extern EIF_BOOLEAN F3_51(EIF_REFERENCE, EIF_REFERENCE);
extern EIF_BOOLEAN F3_52(EIF_REFERENCE);
extern EIF_BOOLEAN F3_53(EIF_REFERENCE, EIF_REFERENCE);
RTOSHF (EIF_REFERENCE,55)
static EIF_REFERENCE F3_55_body(EIF_REFERENCE);
extern EIF_REFERENCE F3_55(EIF_REFERENCE);
RTOSHF (EIF_REFERENCE,56)
static EIF_REFERENCE F3_56_body(EIF_REFERENCE);
extern EIF_REFERENCE F3_56(EIF_REFERENCE);
extern void EIF_Minit3(void);
extern EIF_REFERENCE F785_5128(EIF_REFERENCE);
extern void F785_5127(EIF_REFERENCE);
extern EIF_BOOLEAN F781_4924(EIF_REFERENCE, EIF_REFERENCE);
extern char *(*R3748[])();
extern char *(*R3753[])();
extern char *(*R3755[])();

#ifdef __cplusplus
}
#endif

#endif
