/*
**
** The C code is generated by [ATS/Postiats-0-4-1]
** The starting compilation time is: 2026-10-4: 20h:28m
**
*/

/*
** include runtime header files
*/
#ifndef _ATS_CCOMP_HEADER_NONE_
#include "pats_ccomp_config.h"
#include "pats_ccomp_basics.h"
#include "pats_ccomp_typedefs.h"
#include "pats_ccomp_instrset.h"
#include "pats_ccomp_memalloc.h"
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
#include "pats_ccomp_memalloca.h"
#include "pats_ccomp_exception.h"
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
#endif /* _ATS_CCOMP_HEADER_NONE_ */


/*
** include prelude cats files
*/
#ifndef _ATS_CCOMP_PRELUDE_NONE_
//
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/integer_long.cats"
#include "prelude/CATS/integer_size.cats"
#include "prelude/CATS/integer_short.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/memory.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/strptr.cats"
//
#include "prelude/CATS/fprintf.cats"
//
#include "prelude/CATS/filebas.cats"
//
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/arrayptr.cats"
#include "prelude/CATS/arrayref.cats"
#include "prelude/CATS/matrix.cats"
#include "prelude/CATS/matrixptr.cats"
//
#endif /* _ATS_CCOMP_PRELUDE_NONE_ */
/*
** for user-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER_
//
#include _ATS_CCOMP_PRELUDE_USER_
//
#endif /* _ATS_CCOMP_PRELUDE_USER_ */
/*
** for user2-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER2_
//
#include _ATS_CCOMP_PRELUDE_USER2_
//
#endif /* _ATS_CCOMP_PRELUDE_USER2_ */

/*
staload-prologues(beg)
*/
/*
/cygdrive/c/stupidspeed/tools/ats/libats/libc/SATS/stdio.sats: 1390(line=36, offs=1) -- 1437(line=39, offs=3)
*/

#include \
"libats/libc/CATS/stdio.cats"
/*
/cygdrive/c/stupidspeed/tools/ats/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
/cygdrive/c/stupidspeed/tools/ats/libats/libc/SATS/sys/stat.sats: 1390(line=36, offs=1) -- 1440(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/stat.cats"
/*
/cygdrive/c/stupidspeed/tools/ats/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
/cygdrive/c/stupidspeed/tools/ats/libats/libc/SATS/stdio.sats: 1390(line=36, offs=1) -- 1437(line=39, offs=3)
*/

#include \
"libats/libc/CATS/stdio.cats"
/*
/cygdrive/c/stupidspeed/tools/ats/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
staload-prologues(end)
*/
/*
/cygdrive/c/stupidspeed/exec/ats/01_branches/01_branches.dats: 1026(line=15, offs=1) -- 1652(line=38, offs=3)
*/
ATSextcode_beg()
#include <stdio.h>
#if defined(_WIN32)
#include <windows.h>
static double ss_now_ms (void) {
  static LARGE_INTEGER ss_freq;
  static int ss_have = 0;
  LARGE_INTEGER now;
  if (!ss_have) { QueryPerformanceFrequency(&ss_freq); ss_have = 1; }
  QueryPerformanceCounter(&now);
  return (double)now.QuadPart * 1000.0 / (double)ss_freq.QuadPart;
}
#else
#include <time.h>
static double ss_now_ms (void) {
  struct timespec ts;
  clock_gettime(CLOCK_MONOTONIC, &ts);
  return (double)ts.tv_sec * 1000.0 + (double)ts.tv_nsec / 1000000.0;
}
#endif
static void ss_report (double ms) {
  fprintf(stderr, "TIME_MS=%.3f\n", ms);
}
ATSextcode_end()
/*
typedefs-for-tyrecs-and-tysums(beg)
*/
/*
typedefs-for-tyrecs-and-tysums(end)
*/
/*
dynconlst-declaration(beg)
*/
/*
dynconlst-declaration(end)
*/
/*
dyncstlst-declaration(beg)
*/
ATSdyncst_mac(atspre_g0int2int_int_int)
ATSdyncst_mac(atspre_g0int_lt_int)
ATSdyncst_mac(atspre_g0int_eq_int)
ATSdyncst_mac(atspre_g0int_mod_int)
ATSdyncst_mac(atspre_g0int_add_llint)
ATSdyncst_mac(atspre_g0int_add_int)
ATSdyncst_mac(atspre_g0float_sub_double)
/*
dyncstlst-declaration(end)
*/
/*
dynvalist-implementation(beg)
*/
/*
dynvalist-implementation(end)
*/
/*
exnconlst-declaration(beg)
*/
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
ATSextern()
atsvoid_t0ype
the_atsexncon_initize
(
  atstype_exnconptr d2c, atstype_string exnmsg
) ;
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
/*
exnconlst-declaration(end)
*/
/*
extypelst-declaration(beg)
*/
/*
extypelst-declaration(end)
*/
/*
assumelst-declaration(beg)
*/
#ifndef _ATS_CCOMP_ASSUME_CHECK_NONE_
#endif // #ifndef(_ATS_CCOMP_ASSUME_CHECK_NONE_)
/*
assumelst-declaration(end)
*/
#if(0)
ATSextern()
atsvoid_t0ype
mainats_0_void() ;
#endif // end of [QUALIFIED]

#if(0)
#if(0)
ATSextern()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__lt_g0int_int__1(atstkind_t0ype(atstyvar_type(tk)), atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstatic()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__lt_g0int_int__1__1(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

#if(0)
#if(0)
ATSextern()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__5(atstkind_t0ype(atstyvar_type(tk)), atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstatic()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__5__1(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

ATSstatic()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__5__2(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

ATSstatic()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__5__3(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

/*
/cygdrive/c/stupidspeed/exec/ats/01_branches/01_branches.dats: 1670(line=40, offs=17) -- 2162(line=57, offs=4)
*/
/*
local: 
global: mainats_0_void$0$0(level=0)
local: 
global: 
*/
ATSextern()
atsvoid_t0ype
mainats_0_void()
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret0) ;
ATStmpdec(tmp1, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmpref2, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmpref3, atstkind_t0ype(atstype_llint)) ;
ATStmpdec(tmpref4, atstkind_t0ype(atstype_llint)) ;
ATStmpdec(tmpref5, atstkind_t0ype(atstype_llint)) ;
ATStmpdec(tmpref6, atstkind_t0ype(atstype_llint)) ;
ATStmpdec(tmp7, atstkind_t0ype(atstype_bool)) ;
// ATStmpdec_void(tmp12) ;
ATStmpdec(tmp13, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp18, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp19, atstkind_t0ype(atstype_llint)) ;
ATStmpdec(tmp20, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp23, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp24, atstkind_t0ype(atstype_llint)) ;
ATStmpdec(tmp25, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp28, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp29, atstkind_t0ype(atstype_llint)) ;
ATStmpdec(tmp30, atstkind_t0ype(atstype_llint)) ;
ATStmpdec(tmp31, atstkind_t0ype(atstype_int)) ;
// ATStmpdec_void(tmp32) ;
ATStmpdec(tmp33, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp34, atstkind_t0ype(atstype_double)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /cygdrive/c/stupidspeed/exec/ats/01_branches/01_branches.dats: 1664(line=40, offs=11) -- 2162(line=57, offs=4)
*/
ATSINSflab(__patsflab_main_0_void):
/*
emit_instr: loc0 = /cygdrive/c/stupidspeed/exec/ats/01_branches/01_branches.dats: 1675(line=40, offs=22) -- 2162(line=57, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /cygdrive/c/stupidspeed/exec/ats/01_branches/01_branches.dats: 1693(line=41, offs=15) -- 1724(line=41, offs=46)
*/
ATSINSmove(tmp1, ATSextfcall(ss_now_ms, ())) ;
/*
emit_instr: loc0 = /cygdrive/c/stupidspeed/exec/ats/01_branches/01_branches.dats: 1731(line=42, offs=7) -- 1732(line=42, offs=8)
*/
/*
ATSINStmpdec(tmpref2) ;
*/
/*
emit_instr: loc0 = /cygdrive/c/stupidspeed/exec/ats/01_branches/01_branches.dats: 1740(line=42, offs=16) -- 1741(line=42, offs=17)
*/
ATSINSmove(tmpref2, ATSPMVi0nt(0)) ;
/*
emit_instr: loc0 = /cygdrive/c/stupidspeed/exec/ats/01_branches/01_branches.dats: 1748(line=43, offs=7) -- 1749(line=43, offs=8)
*/
/*
ATSINStmpdec(tmpref3) ;
*/
/*
emit_instr: loc0 = /cygdrive/c/stupidspeed/exec/ats/01_branches/01_branches.dats: 1759(line=43, offs=18) -- 1762(line=43, offs=21)
*/
ATSINSmove(tmpref3, ATSPMVi0nt(0LL)) ;
/*
emit_instr: loc0 = /cygdrive/c/stupidspeed/exec/ats/01_branches/01_branches.dats: 1769(line=44, offs=7) -- 1770(line=44, offs=8)
*/
/*
ATSINStmpdec(tmpref4) ;
*/
/*
emit_instr: loc0 = /cygdrive/c/stupidspeed/exec/ats/01_branches/01_branches.dats: 1780(line=44, offs=18) -- 1783(line=44, offs=21)
*/
ATSINSmove(tmpref4, ATSPMVi0nt(0LL)) ;
/*
emit_instr: loc0 = /cygdrive/c/stupidspeed/exec/ats/01_branches/01_branches.dats: 1790(line=45, offs=7) -- 1791(line=45, offs=8)
*/
/*
ATSINStmpdec(tmpref5) ;
*/
/*
emit_instr: loc0 = /cygdrive/c/stupidspeed/exec/ats/01_branches/01_branches.dats: 1801(line=45, offs=18) -- 1804(line=45, offs=21)
*/
ATSINSmove(tmpref5, ATSPMVi0nt(0LL)) ;
/*
emit_instr: loc0 = /cygdrive/c/stupidspeed/exec/ats/01_branches/01_branches.dats: 1811(line=46, offs=7) -- 1812(line=46, offs=8)
*/
/*
ATSINStmpdec(tmpref6) ;
*/
/*
emit_instr: loc0 = /cygdrive/c/stupidspeed/exec/ats/01_branches/01_branches.dats: 1822(line=46, offs=18) -- 1825(line=46, offs=21)
*/
ATSINSmove(tmpref6, ATSPMVi0nt(0LL)) ;
/*
letpush(end)
*/

/*
emit_instr: loc0 = /cygdrive/c/stupidspeed/exec/ats/01_branches/01_branches.dats: 1831(line=48, offs=3) -- 2017(line=54, offs=4)
*/
/*
** loop-init(beg)
*/
/* (*nothing*) */
/*
** loop-init(end)
*/
ATSloop_open(__atstmplab0, __atstmplab1, __atstmplab0)
/*
emit_instr: loc0 = /cygdrive/c/stupidspeed/exec/ats/01_branches/01_branches.dats: 1838(line=48, offs=10) -- 1851(line=48, offs=23)
*/
ATSINSmove(tmp7, ATSLIB_056_prelude__lt_g0int_int__1__1(tmpref2, ATSPMVi0nt(100000000))) ;

ATSif(ATSCKnot(tmp7)) ATSbreak() ;
/*
emit_instr: loc0 = /cygdrive/c/stupidspeed/exec/ats/01_branches/01_branches.dats: 1862(line=49, offs=8) -- 1869(line=49, offs=15)
*/
ATSINSmove(tmp18, atspre_g0int_mod_int(tmpref2, ATSPMVi0nt(3))) ;

/*
emit_instr: loc0 = /cygdrive/c/stupidspeed/exec/ats/01_branches/01_branches.dats: 1862(line=49, offs=8) -- 1873(line=49, offs=19)
*/
ATSINSmove(tmp13, ATSLIB_056_prelude__eq_g0int_int__5__1(tmp18, ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = /cygdrive/c/stupidspeed/exec/ats/01_branches/01_branches.dats: 1859(line=49, offs=5) -- 1997(line=52, offs=22)
*/
ATSif(
tmp13
) ATSthen() {
/*
emit_instr: loc0 = /cygdrive/c/stupidspeed/exec/ats/01_branches/01_branches.dats: 1884(line=49, offs=30) -- 1891(line=49, offs=37)
*/
ATSINSmove(tmp19, atspre_g0int_add_llint(tmpref3, ATSPMVi0nt(1LL))) ;

/*
emit_instr: loc0 = /cygdrive/c/stupidspeed/exec/ats/01_branches/01_branches.dats: 1879(line=49, offs=25) -- 1891(line=49, offs=37)
*/
ATSINSstore(tmpref3, tmp19) ;
/*
emit_instr: loc0 = /cygdrive/c/stupidspeed/exec/ats/01_branches/01_branches.dats: 1879(line=49, offs=25) -- 1891(line=49, offs=37)
*/
ATSINSmove_void(tmp12, ATSPMVempty()) ;
} ATSelse() {
/*
emit_instr: loc0 = /cygdrive/c/stupidspeed/exec/ats/01_branches/01_branches.dats: 1904(line=50, offs=13) -- 1911(line=50, offs=20)
*/
ATSINSmove(tmp23, atspre_g0int_mod_int(tmpref2, ATSPMVi0nt(5))) ;

/*
emit_instr: loc0 = /cygdrive/c/stupidspeed/exec/ats/01_branches/01_branches.dats: 1904(line=50, offs=13) -- 1915(line=50, offs=24)
*/
ATSINSmove(tmp20, ATSLIB_056_prelude__eq_g0int_int__5__2(tmp23, ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = /cygdrive/c/stupidspeed/exec/ats/01_branches/01_branches.dats: 1901(line=50, offs=10) -- 1997(line=52, offs=22)
*/
ATSif(
tmp20
) ATSthen() {
/*
emit_instr: loc0 = /cygdrive/c/stupidspeed/exec/ats/01_branches/01_branches.dats: 1926(line=50, offs=35) -- 1933(line=50, offs=42)
*/
ATSINSmove(tmp24, atspre_g0int_add_llint(tmpref4, ATSPMVi0nt(1LL))) ;

/*
emit_instr: loc0 = /cygdrive/c/stupidspeed/exec/ats/01_branches/01_branches.dats: 1921(line=50, offs=30) -- 1933(line=50, offs=42)
*/
ATSINSstore(tmpref4, tmp24) ;
/*
emit_instr: loc0 = /cygdrive/c/stupidspeed/exec/ats/01_branches/01_branches.dats: 1921(line=50, offs=30) -- 1933(line=50, offs=42)
*/
ATSINSmove_void(tmp12, ATSPMVempty()) ;
} ATSelse() {
/*
emit_instr: loc0 = /cygdrive/c/stupidspeed/exec/ats/01_branches/01_branches.dats: 1946(line=51, offs=13) -- 1953(line=51, offs=20)
*/
ATSINSmove(tmp28, atspre_g0int_mod_int(tmpref2, ATSPMVi0nt(7))) ;

/*
emit_instr: loc0 = /cygdrive/c/stupidspeed/exec/ats/01_branches/01_branches.dats: 1946(line=51, offs=13) -- 1957(line=51, offs=24)
*/
ATSINSmove(tmp25, ATSLIB_056_prelude__eq_g0int_int__5__3(tmp28, ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = /cygdrive/c/stupidspeed/exec/ats/01_branches/01_branches.dats: 1943(line=51, offs=10) -- 1997(line=52, offs=22)
*/
ATSif(
tmp25
) ATSthen() {
/*
emit_instr: loc0 = /cygdrive/c/stupidspeed/exec/ats/01_branches/01_branches.dats: 1968(line=51, offs=35) -- 1975(line=51, offs=42)
*/
ATSINSmove(tmp29, atspre_g0int_add_llint(tmpref5, ATSPMVi0nt(1LL))) ;

/*
emit_instr: loc0 = /cygdrive/c/stupidspeed/exec/ats/01_branches/01_branches.dats: 1963(line=51, offs=30) -- 1975(line=51, offs=42)
*/
ATSINSstore(tmpref5, tmp29) ;
/*
emit_instr: loc0 = /cygdrive/c/stupidspeed/exec/ats/01_branches/01_branches.dats: 1963(line=51, offs=30) -- 1975(line=51, offs=42)
*/
ATSINSmove_void(tmp12, ATSPMVempty()) ;
} ATSelse() {
/*
emit_instr: loc0 = /cygdrive/c/stupidspeed/exec/ats/01_branches/01_branches.dats: 1990(line=52, offs=15) -- 1997(line=52, offs=22)
*/
ATSINSmove(tmp30, atspre_g0int_add_llint(tmpref6, ATSPMVi0nt(1LL))) ;

/*
emit_instr: loc0 = /cygdrive/c/stupidspeed/exec/ats/01_branches/01_branches.dats: 1985(line=52, offs=10) -- 1997(line=52, offs=22)
*/
ATSINSstore(tmpref6, tmp30) ;
/*
emit_instr: loc0 = /cygdrive/c/stupidspeed/exec/ats/01_branches/01_branches.dats: 1985(line=52, offs=10) -- 1997(line=52, offs=22)
*/
ATSINSmove_void(tmp12, ATSPMVempty()) ;
} /* ATSendif */
} /* ATSendif */
} /* ATSendif */
/*
emit_instr: loc0 = /cygdrive/c/stupidspeed/exec/ats/01_branches/01_branches.dats: 2008(line=53, offs=10) -- 2013(line=53, offs=15)
*/
ATSINSmove(tmp31, atspre_g0int_add_int(tmpref2, ATSPMVi0nt(1))) ;

/*
emit_instr: loc0 = /cygdrive/c/stupidspeed/exec/ats/01_branches/01_branches.dats: 2003(line=53, offs=5) -- 2013(line=53, offs=15)
*/
ATSINSstore(tmpref2, tmp31) ;
ATSloop_close(__atstmplab0, __atstmplab1, __atstmplab0) ;

/*
emit_instr: loc0 = /cygdrive/c/stupidspeed/exec/ats/01_branches/01_branches.dats: 2051(line=55, offs=33) -- 2082(line=55, offs=64)
*/
ATSINSmove(tmp34, ATSextfcall(ss_now_ms, ())) ;
/*
emit_instr: loc0 = /cygdrive/c/stupidspeed/exec/ats/01_branches/01_branches.dats: 2051(line=55, offs=33) -- 2090(line=55, offs=72)
*/
ATSINSmove(tmp33, atspre_g0float_sub_double(tmp34, tmp1)) ;

/*
emit_instr: loc0 = /cygdrive/c/stupidspeed/exec/ats/01_branches/01_branches.dats: 2021(line=55, offs=3) -- 2091(line=55, offs=73)
*/
ATSINSmove_void(tmp32, ATSextfcall(ss_report, (tmp33))) ;
/*
emit_instr: loc0 = /cygdrive/c/stupidspeed/exec/ats/01_branches/01_branches.dats: 2095(line=56, offs=3) -- 2158(line=56, offs=66)
*/
ATSINSmove_void(tmpret0, ATSextfcall(printf, (ATSPMVstring("%lld %lld %lld %lld\n"), tmpref3, tmpref4, tmpref5, tmpref6))) ;
/*
emit_instr: loc0 = /cygdrive/c/stupidspeed/exec/ats/01_branches/01_branches.dats: 1675(line=40, offs=22) -- 2162(line=57, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn_void(tmpret0) ;
} /* end of [mainats_0_void] */

#if(0)
/*
/cygdrive/c/stupidspeed/tools/ats/prelude/DATS/integer.dats: 11941(line=617, offs=3) -- 11980(line=617, offs=42)
*/
/*
local: 
global: lt_g0int_int$1$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = tk(4630)
tmparg = S2Evar(tk(4630))
tmpsub = None()
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__lt_g0int_int__1(atstkind_t0ype(atstyvar_type(tk)) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret8, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp9, atstkind_t0ype(atstyvar_type(tk))) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /cygdrive/c/stupidspeed/tools/ats/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11926(line=616, offs=1) -- 11980(line=617, offs=42)
*/
ATSINSflab(__patsflab_lt_g0int_int):
/*
emit_instr: loc0 = /cygdrive/c/stupidspeed/tools/ats/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11967(line=617, offs=29) -- 11978(line=617, offs=40)
*/
ATSINSmove(tmp9, PMVtmpltcst(g0int2int<S2Eextkind(atstype_int), S2Evar(tk(4630))>)(arg1)) ;

/*
emit_instr: loc0 = /cygdrive/c/stupidspeed/tools/ats/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11950(line=617, offs=12) -- 11980(line=617, offs=42)
*/
ATSINSmove(tmpret8, PMVtmpltcst(g0int_lt<S2Evar(tk(4630))>)(arg0, tmp9)) ;

ATSfunbody_end()
ATSreturn(tmpret8) ;
} /* end of [ATSLIB_056_prelude__lt_g0int_int__1] */
#endif // end of [TEMPLATE]

/*
/cygdrive/c/stupidspeed/tools/ats/prelude/DATS/integer.dats: 11941(line=617, offs=3) -- 11980(line=617, offs=42)
*/
/*
local: 
global: lt_g0int_int$1$1(level=1)
local: 
global: 
*/
ATSstatic()
/*
imparg = tk(4630)
tmparg = S2Evar(tk(4630))
tmpsub = Some(tk(4630) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__lt_g0int_int__1__1(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret8__1, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp9__1, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /cygdrive/c/stupidspeed/tools/ats/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11926(line=616, offs=1) -- 11980(line=617, offs=42)
*/
ATSINSflab(__patsflab_lt_g0int_int):
/*
emit_instr: loc0 = /cygdrive/c/stupidspeed/tools/ats/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11967(line=617, offs=29) -- 11978(line=617, offs=40)
*/
ATSINSmove(tmp9__1, atspre_g0int2int_int_int(arg1)) ;

/*
emit_instr: loc0 = /cygdrive/c/stupidspeed/tools/ats/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11950(line=617, offs=12) -- 11980(line=617, offs=42)
*/
ATSINSmove(tmpret8__1, atspre_g0int_lt_int(arg0, tmp9__1)) ;

ATSfunbody_end()
ATSreturn(tmpret8__1) ;
} /* end of [ATSLIB_056_prelude__lt_g0int_int__1__1] */

#if(0)
/*
/cygdrive/c/stupidspeed/tools/ats/prelude/DATS/integer.dats: 12259(line=635, offs=3) -- 12298(line=635, offs=42)
*/
/*
local: 
global: eq_g0int_int$5$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = tk(4634)
tmparg = S2Evar(tk(4634))
tmpsub = None()
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__5(atstkind_t0ype(atstyvar_type(tk)) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret14, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp15, atstkind_t0ype(atstyvar_type(tk))) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /cygdrive/c/stupidspeed/tools/ats/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12244(line=634, offs=1) -- 12298(line=635, offs=42)
*/
ATSINSflab(__patsflab_eq_g0int_int):
/*
emit_instr: loc0 = /cygdrive/c/stupidspeed/tools/ats/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12285(line=635, offs=29) -- 12296(line=635, offs=40)
*/
ATSINSmove(tmp15, PMVtmpltcst(g0int2int<S2Eextkind(atstype_int), S2Evar(tk(4634))>)(arg1)) ;

/*
emit_instr: loc0 = /cygdrive/c/stupidspeed/tools/ats/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12268(line=635, offs=12) -- 12298(line=635, offs=42)
*/
ATSINSmove(tmpret14, PMVtmpltcst(g0int_eq<S2Evar(tk(4634))>)(arg0, tmp15)) ;

ATSfunbody_end()
ATSreturn(tmpret14) ;
} /* end of [ATSLIB_056_prelude__eq_g0int_int__5] */
#endif // end of [TEMPLATE]

/*
/cygdrive/c/stupidspeed/tools/ats/prelude/DATS/integer.dats: 12259(line=635, offs=3) -- 12298(line=635, offs=42)
*/
/*
local: 
global: eq_g0int_int$5$1(level=1)
local: 
global: 
*/
ATSstatic()
/*
imparg = tk(4634)
tmparg = S2Evar(tk(4634))
tmpsub = Some(tk(4634) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__5__1(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret14__1, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp15__1, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /cygdrive/c/stupidspeed/tools/ats/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12244(line=634, offs=1) -- 12298(line=635, offs=42)
*/
ATSINSflab(__patsflab_eq_g0int_int):
/*
emit_instr: loc0 = /cygdrive/c/stupidspeed/tools/ats/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12285(line=635, offs=29) -- 12296(line=635, offs=40)
*/
ATSINSmove(tmp15__1, atspre_g0int2int_int_int(arg1)) ;

/*
emit_instr: loc0 = /cygdrive/c/stupidspeed/tools/ats/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12268(line=635, offs=12) -- 12298(line=635, offs=42)
*/
ATSINSmove(tmpret14__1, atspre_g0int_eq_int(arg0, tmp15__1)) ;

ATSfunbody_end()
ATSreturn(tmpret14__1) ;
} /* end of [ATSLIB_056_prelude__eq_g0int_int__5__1] */

/*
/cygdrive/c/stupidspeed/tools/ats/prelude/DATS/integer.dats: 12259(line=635, offs=3) -- 12298(line=635, offs=42)
*/
/*
local: 
global: eq_g0int_int$5$2(level=1)
local: 
global: 
*/
ATSstatic()
/*
imparg = tk(4634)
tmparg = S2Evar(tk(4634))
tmpsub = Some(tk(4634) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__5__2(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret14__2, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp15__2, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /cygdrive/c/stupidspeed/tools/ats/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12244(line=634, offs=1) -- 12298(line=635, offs=42)
*/
ATSINSflab(__patsflab_eq_g0int_int):
/*
emit_instr: loc0 = /cygdrive/c/stupidspeed/tools/ats/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12285(line=635, offs=29) -- 12296(line=635, offs=40)
*/
ATSINSmove(tmp15__2, atspre_g0int2int_int_int(arg1)) ;

/*
emit_instr: loc0 = /cygdrive/c/stupidspeed/tools/ats/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12268(line=635, offs=12) -- 12298(line=635, offs=42)
*/
ATSINSmove(tmpret14__2, atspre_g0int_eq_int(arg0, tmp15__2)) ;

ATSfunbody_end()
ATSreturn(tmpret14__2) ;
} /* end of [ATSLIB_056_prelude__eq_g0int_int__5__2] */

/*
/cygdrive/c/stupidspeed/tools/ats/prelude/DATS/integer.dats: 12259(line=635, offs=3) -- 12298(line=635, offs=42)
*/
/*
local: 
global: eq_g0int_int$5$3(level=1)
local: 
global: 
*/
ATSstatic()
/*
imparg = tk(4634)
tmparg = S2Evar(tk(4634))
tmpsub = Some(tk(4634) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__5__3(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret14__3, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp15__3, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /cygdrive/c/stupidspeed/tools/ats/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12244(line=634, offs=1) -- 12298(line=635, offs=42)
*/
ATSINSflab(__patsflab_eq_g0int_int):
/*
emit_instr: loc0 = /cygdrive/c/stupidspeed/tools/ats/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12285(line=635, offs=29) -- 12296(line=635, offs=40)
*/
ATSINSmove(tmp15__3, atspre_g0int2int_int_int(arg1)) ;

/*
emit_instr: loc0 = /cygdrive/c/stupidspeed/tools/ats/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12268(line=635, offs=12) -- 12298(line=635, offs=42)
*/
ATSINSmove(tmpret14__3, atspre_g0int_eq_int(arg0, tmp15__3)) ;

ATSfunbody_end()
ATSreturn(tmpret14__3) ;
} /* end of [ATSLIB_056_prelude__eq_g0int_int__5__3] */

/*
** for initialization(dynloading)
*/
ATSdynloadflag_minit(_057_cygdrive_057_c_057_stupidspeed_057_exec_057_ats_057_01_branches_057_01_branches_056_dats__dynloadflag) ;
ATSextern()
atsvoid_t0ype
_057_cygdrive_057_c_057_stupidspeed_057_exec_057_ats_057_01_branches_057_01_branches_056_dats__dynload()
{
ATSfunbody_beg()
ATSdynload(/*void*/)
ATSdynloadflag_sta(
_057_cygdrive_057_c_057_stupidspeed_057_exec_057_ats_057_01_branches_057_01_branches_056_dats__dynloadflag
) ;
ATSif(
ATSCKiseqz(
_057_cygdrive_057_c_057_stupidspeed_057_exec_057_ats_057_01_branches_057_01_branches_056_dats__dynloadflag
)
) ATSthen() {
ATSdynloadset(_057_cygdrive_057_c_057_stupidspeed_057_exec_057_ats_057_01_branches_057_01_branches_056_dats__dynloadflag) ;
/*
dynexnlst-initize(beg)
*/
/*
dynexnlst-initize(end)
*/
} /* ATSendif */
ATSfunbody_end()
ATSreturn_void(tmpret_void) ;
} /* end of [*_dynload] */

/*
** the ATS runtime
*/
#ifndef _ATS_CCOMP_RUNTIME_NONE_
#include "pats_ccomp_runtime.c"
#include "pats_ccomp_runtime_memalloc.c"
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
#include "pats_ccomp_runtime2_dats.c"
#ifndef _ATS_CCOMP_RUNTIME_TRYWITH_NONE_
#include "pats_ccomp_runtime_trywith.c"
#endif /* _ATS_CCOMP_RUNTIME_TRYWITH_NONE_ */
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
#endif /* _ATS_CCOMP_RUNTIME_NONE_ */

/*
** the [main] implementation
*/
int
main
(
int argc, char **argv, char **envp
) {
int err = 0 ;
_057_cygdrive_057_c_057_stupidspeed_057_exec_057_ats_057_01_branches_057_01_branches_056_dats__dynload() ;
ATSmainats_0_void(err) ;
return (err) ;
} /* end of [main] */

/* ****** ****** */

/* end-of-compilation-unit */
