
#ifndef _C1_en2_
#define _C1_en2_

#ifdef __cplusplus
extern "C" {
#endif

extern void F2_35(EIF_REFERENCE, EIF_REFERENCE);
extern EIF_REFERENCE F2_37(EIF_REFERENCE);
extern EIF_REFERENCE F2_38(EIF_REFERENCE);
extern void F2_41(EIF_REFERENCE, EIF_REFERENCE, EIF_REFERENCE);
extern EIF_BOOLEAN F2_42(EIF_REFERENCE);
extern EIF_BOOLEAN F2_44(EIF_REFERENCE, EIF_REFERENCE);
extern EIF_BOOLEAN F2_45(EIF_REFERENCE);
extern EIF_BOOLEAN F2_46(EIF_REFERENCE, EIF_REFERENCE);
RTOSHF (EIF_REFERENCE,48)
static EIF_REFERENCE F2_48_body(EIF_REFERENCE);
extern EIF_REFERENCE F2_48(EIF_REFERENCE);
RTOSHF (EIF_REFERENCE,49)
static EIF_REFERENCE F2_49_body(EIF_REFERENCE);
extern EIF_REFERENCE F2_49(EIF_REFERENCE);
extern void EIF_Minit2(void);
extern EIF_REFERENCE F785_5128(EIF_REFERENCE);
extern void F785_5127(EIF_REFERENCE);
extern EIF_BOOLEAN F781_4924(EIF_REFERENCE, EIF_REFERENCE);
extern char *(*R3748[])();
extern char *(*R3753[])();
extern char *(*R3755[])();

#ifdef __cplusplus
}
#endif

#endif
