
#ifndef _C1_sy3_
#define _C1_sy3_

#ifdef __cplusplus
extern "C" {
#endif

RTOSHF (EIF_REFERENCE,51)
static EIF_REFERENCE F3_51_body(EIF_REFERENCE);
extern EIF_REFERENCE F3_51(EIF_REFERENCE);
RTOSHF (EIF_REFERENCE,52)
static EIF_REFERENCE F3_52_body(EIF_REFERENCE);
extern EIF_REFERENCE F3_52(EIF_REFERENCE);
RTOSHF (EIF_REFERENCE,54)
static EIF_REFERENCE F3_54_body(EIF_REFERENCE);
extern EIF_REFERENCE F3_54(EIF_REFERENCE);
RTOSHF (EIF_REFERENCE,56)
static EIF_REFERENCE F3_56_body(EIF_REFERENCE);
extern EIF_REFERENCE F3_56(EIF_REFERENCE);
extern void EIF_Minit3(void);
extern EIF_REFERENCE F4_60(EIF_REFERENCE);
extern EIF_REFERENCE F4_58(EIF_REFERENCE);
extern EIF_REFERENCE F35_581(EIF_REFERENCE);
extern void F2_35(EIF_REFERENCE, EIF_REFERENCE);
RTOSHF(EIF_REFERENCE,58)
RTOSHF(EIF_REFERENCE,60)

#ifdef __cplusplus
}
#endif

#endif
