// Generated by Haxe 4.3.7

#pragma warning disable 109, 114, 219, 429, 168, 162
public class T15_file_write : global::haxe.lang.HxObject {
	
	public static void Main(){
		global::cs.Boot.init();
		{
			global::T15_file_write.main();
			global::sys.thread._Thread.Thread_Impl_.processEvents();
		}
		;
	}
	static T15_file_write() {
		unchecked{
			#line 14 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T15_file_write\\T15_file_write.hx"
			global::T15_file_write.CHUNK = 1048576;
			global::T15_file_write.REPEATS = 50;
		}
	}
	#line default
	
	public T15_file_write(global::haxe.lang.EmptyObject empty) {
	}
	
	
	public T15_file_write() {
		#line 13 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T15_file_write\\T15_file_write.hx"
		global::T15_file_write.__hx_ctor__T15_file_write(this);
	}
	#line default
	
	protected static void __hx_ctor__T15_file_write(global::T15_file_write __hx_this) {
	}
	
	
	public static int CHUNK;
	
	public static int REPEATS;
	
	public static void main() {
		unchecked {
			#line 19 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T15_file_write\\T15_file_write.hx"
			double t0 = global::Sys.time();
			#line 39 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T15_file_write\\T15_file_write.hx"
			global::haxe.io.Bytes buf = global::haxe.io.Bytes.alloc(1048576);
			{
				#line 40 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T15_file_write\\T15_file_write.hx"
				int _g = 0;
				#line 40 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T15_file_write\\T15_file_write.hx"
				while (( _g < 1048576 )) {
					#line 40 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T15_file_write\\T15_file_write.hx"
					int i = _g++;
					buf.b[i] = ((byte) (( i % 256 )) );
				}
				
			}
			
			#line 44 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T15_file_write\\T15_file_write.hx"
			global::sys.io.FileOutput f = global::sys.io.File.write("out.bin", new global::haxe.lang.Null<bool>(true, true));
			#line 46 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T15_file_write\\T15_file_write.hx"
			int written = 0;
			{
				#line 47 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T15_file_write\\T15_file_write.hx"
				int _g1 = 0;
				#line 47 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T15_file_write\\T15_file_write.hx"
				while (( _g1 < 50 )) {
					#line 47 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T15_file_write\\T15_file_write.hx"
					int i1 = _g1++;
					written += f.writeBytes(buf, 0, 1048576);
				}
				
			}
			
			#line 51 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T15_file_write\\T15_file_write.hx"
			f.flush();
			f.close();
			#line 55 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T15_file_write\\T15_file_write.hx"
			double t1 = global::Sys.time();
			global::Out.err(global::haxe.lang.Runtime.concat(global::haxe.lang.Runtime.concat("TIME_MS=", global::haxe.lang.Runtime.toString(( (( t1 - t0 )) * 1000.0 ))), "\n"));
			#line 57 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T15_file_write\\T15_file_write.hx"
			global::Out.line(written);
		}
		#line default
	}
	
	
}


