
#ifndef _C1_co19_
#define _C1_co19_

#ifdef __cplusplus
extern "C" {
#endif

RTOSHF (EIF_REFERENCE,534)
static EIF_REFERENCE F31_534_body(EIF_REFERENCE);
extern EIF_REFERENCE F31_534(EIF_REFERENCE);
RTOSHF (EIF_REFERENCE,535)
static EIF_REFERENCE F31_535_body(EIF_REFERENCE);
extern EIF_REFERENCE F31_535(EIF_REFERENCE);
RTOSHF (EIF_REFERENCE,536)
static EIF_REFERENCE F31_536_body(EIF_REFERENCE);
extern EIF_REFERENCE F31_536(EIF_REFERENCE);
RTOSHF (EIF_REFERENCE,537)
static EIF_REFERENCE F31_537_body(EIF_REFERENCE);
extern EIF_REFERENCE F31_537(EIF_REFERENCE);
extern void EIF_Minit19(void);
extern EIF_REFERENCE F4_60(EIF_REFERENCE);
extern EIF_REFERENCE F4_63(EIF_REFERENCE);
extern EIF_REFERENCE F4_58(EIF_REFERENCE);
extern EIF_REFERENCE F784_5048(EIF_REFERENCE);
extern void F595_2973(EIF_REFERENCE, EIF_REFERENCE, EIF_REFERENCE);
extern EIF_REFERENCE F4_62(EIF_REFERENCE);
extern void F599_3039(EIF_REFERENCE, EIF_INTEGER_32);
extern EIF_REFERENCE F4_57(EIF_REFERENCE);
extern EIF_REFERENCE F4_61(EIF_REFERENCE);
extern EIF_REFERENCE F4_64(EIF_REFERENCE);
extern EIF_REFERENCE F4_59(EIF_REFERENCE);
RTOSHF(EIF_REFERENCE,57)
RTOSHF(EIF_REFERENCE,58)
RTOSHF(EIF_REFERENCE,59)
RTOSHF(EIF_REFERENCE,61)
RTOSHF(EIF_REFERENCE,60)
RTOSHF(EIF_REFERENCE,62)
RTOSHF(EIF_REFERENCE,63)
RTOSHF(EIF_REFERENCE,64)

#ifdef __cplusplus
}
#endif

#endif
