
#ifndef _C1_sy2_
#define _C1_sy2_

#ifdef __cplusplus
extern "C" {
#endif

RTOSHF (EIF_REFERENCE,36)
static EIF_REFERENCE F2_36_body(EIF_REFERENCE);
extern EIF_REFERENCE F2_36(EIF_REFERENCE);
RTOSHF (EIF_REFERENCE,37)
static EIF_REFERENCE F2_37_body(EIF_REFERENCE);
extern EIF_REFERENCE F2_37(EIF_REFERENCE);
RTOSHF (EIF_REFERENCE,39)
static EIF_REFERENCE F2_39_body(EIF_REFERENCE);
extern EIF_REFERENCE F2_39(EIF_REFERENCE);
RTOSHF (EIF_REFERENCE,41)
static EIF_REFERENCE F2_41_body(EIF_REFERENCE);
extern EIF_REFERENCE F2_41(EIF_REFERENCE);
extern void EIF_Minit2(void);
extern EIF_REFERENCE F4_60(EIF_REFERENCE);
extern void F3_42(EIF_REFERENCE, EIF_REFERENCE);
extern EIF_REFERENCE F4_58(EIF_REFERENCE);
extern EIF_REFERENCE F36_583(EIF_REFERENCE);
RTOSHF(EIF_REFERENCE,58)
RTOSHF(EIF_REFERENCE,60)

#ifdef __cplusplus
}
#endif

#endif
