<?php
/**
 * Generated by Haxe 4.3.7
 */

use \haxe\io\_BytesData\Container;
use \php\Boot;
use \haxe\io\Error;
use \haxe\Exception as HaxeException;
use \haxe\io\Bytes;

class T06_char_count {
	/**
	 * @return void
	 */
	public static function main () {
		#T06_char_count.hx:12: characters 9-37
		$t0 = microtime(true);
		#T06_char_count.hx:13: characters 9-27
		$blockLen = 10;
		#T06_char_count.hx:14: characters 9-32
		$repeats = 10000000;
		#T06_char_count.hx:15: characters 21-57
		$block = strlen("abcdefghij");
		#T06_char_count.hx:15: characters 9-58
		$block1 = new Bytes($block, new Container("abcdefghij"));
		#T06_char_count.hx:16: characters 9-60
		$text = Bytes::alloc($repeats * $blockLen);
		#T06_char_count.hx:18: characters 19-23
		$_g = 0;
		#T06_char_count.hx:18: characters 23-30
		$_g1 = $repeats;
		#T06_char_count.hx:18: lines 18-20
		while ($_g < $_g1) {
			#T06_char_count.hx:18: characters 19-30
			$i = $_g++;
			#T06_char_count.hx:19: characters 13-56
			$pos = $i * $blockLen;
			if (($pos < 0) || ($blockLen < 0) || (($pos + $blockLen) > $text->length) || ($blockLen > $block1->length)) {
				throw HaxeException::thrown(Error::OutsideBounds());
			} else {
				$this1 = $text->b;
				$src = $block1->b;
				$this1->s = ((substr($this1->s, 0, $pos) . substr($src->s, 0, $blockLen)) . substr($this1->s, $pos + $blockLen));
			}
		}
		#T06_char_count.hx:22: characters 9-26
		$a = 97;
		#T06_char_count.hx:23: characters 9-26
		$e = 101;
		#T06_char_count.hx:24: characters 9-26
		$h = 104;
		#T06_char_count.hx:26: characters 9-23
		$count = 0;
		#T06_char_count.hx:27: characters 19-23
		$_g = 0;
		#T06_char_count.hx:27: characters 23-34
		$_g1 = $text->length;
		#T06_char_count.hx:27: lines 27-36
		while ($_g < $_g1) {
			#T06_char_count.hx:27: characters 19-34
			$i = $_g++;
			#T06_char_count.hx:28: characters 13-34
			$ch = ord($text->b->s[$i]);
			#T06_char_count.hx:29: lines 29-35
			if ($ch === $a) {
				#T06_char_count.hx:30: characters 17-25
				continue;
			} else if ($ch === $e) {
				#T06_char_count.hx:32: characters 17-25
				continue;
			} else if ($ch === $h) {
				#T06_char_count.hx:34: characters 17-27
				++$count;
			}
		}
		#T06_char_count.hx:38: characters 9-37
		$t1 = microtime(true);
		#T06_char_count.hx:39: characters 9-58
		\Out::err("TIME_MS=" . (($t1 - $t0) * 1000.0) . "\x0A");
		#T06_char_count.hx:40: characters 9-24
		\Out::line($count);
	}
}

Boot::registerClass(T06_char_count::class, 'T06_char_count');
