// Generated by Haxe 4.3.7

#pragma warning disable 109, 114, 219, 429, 168, 162
public class T04_array_sum : global::haxe.lang.HxObject {
	
	public static void Main(){
		global::cs.Boot.init();
		{
			global::T04_array_sum.main();
			global::sys.thread._Thread.Thread_Impl_.processEvents();
		}
		;
	}
	public T04_array_sum(global::haxe.lang.EmptyObject empty) {
	}
	
	
	public T04_array_sum() {
		#line 8 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T04_array_sum\\T04_array_sum.hx"
		global::T04_array_sum.__hx_ctor__T04_array_sum(this);
	}
	#line default
	
	protected static void __hx_ctor__T04_array_sum(global::T04_array_sum __hx_this) {
	}
	
	
	public static void main() {
		unchecked {
			#line 11 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T04_array_sum\\T04_array_sum.hx"
			double t0 = global::Sys.time();
			int n = 1000000;
			#line 13 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T04_array_sum\\T04_array_sum.hx"
			global::Array<int> array = new global::Array<int>();
			#line 15 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T04_array_sum\\T04_array_sum.hx"
			{
				#line 15 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T04_array_sum\\T04_array_sum.hx"
				int _g = 0;
				#line 15 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T04_array_sum\\T04_array_sum.hx"
				int _g1 = n;
				#line 15 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T04_array_sum\\T04_array_sum.hx"
				while (( _g < _g1 )) {
					#line 15 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T04_array_sum\\T04_array_sum.hx"
					int i = _g++;
					array[i] = i;
				}
				
			}
			
			#line 19 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T04_array_sum\\T04_array_sum.hx"
			long total = ((long) (0) );
			{
				#line 20 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T04_array_sum\\T04_array_sum.hx"
				int _g2 = 0;
				#line 20 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T04_array_sum\\T04_array_sum.hx"
				int _g3 = n;
				#line 20 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T04_array_sum\\T04_array_sum.hx"
				while (( _g2 < _g3 )) {
					#line 20 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T04_array_sum\\T04_array_sum.hx"
					int i1 = _g2++;
					total = ((long) (( ((long) (total) ) + ((long) (array[i1]) ) )) );
				}
				
			}
			
			#line 24 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T04_array_sum\\T04_array_sum.hx"
			double t1 = global::Sys.time();
			global::Out.err(global::haxe.lang.Runtime.concat(global::haxe.lang.Runtime.concat("TIME_MS=", global::haxe.lang.Runtime.toString(( (( t1 - t0 )) * 1000.0 ))), "\n"));
			#line 26 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T04_array_sum\\T04_array_sum.hx"
			global::Out.line(total);
		}
		#line default
	}
	
	
}


