// Generated by Haxe 4.3.7

#pragma warning disable 109, 114, 219, 429, 168, 162
public class T12_matrix_add : global::haxe.lang.HxObject {
	
	public static void Main(){
		global::cs.Boot.init();
		{
			global::T12_matrix_add.main();
			global::sys.thread._Thread.Thread_Impl_.processEvents();
		}
		;
	}
	public T12_matrix_add(global::haxe.lang.EmptyObject empty) {
	}
	
	
	public T12_matrix_add() {
		#line 9 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T12_matrix_add\\T12_matrix_add.hx"
		global::T12_matrix_add.__hx_ctor__T12_matrix_add(this);
	}
	#line default
	
	protected static void __hx_ctor__T12_matrix_add(global::T12_matrix_add __hx_this) {
	}
	
	
	public static void main() {
		unchecked {
			#line 12 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T12_matrix_add\\T12_matrix_add.hx"
			double t0 = global::Sys.time();
			int n = 1000;
			#line 14 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T12_matrix_add\\T12_matrix_add.hx"
			int elems = ( n * n );
			#line 16 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T12_matrix_add\\T12_matrix_add.hx"
			global::Array<int> a = new global::Array<int>();
			global::Array<int> b = new global::Array<int>();
			#line 18 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T12_matrix_add\\T12_matrix_add.hx"
			global::Array<int> c = new global::Array<int>();
			#line 20 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T12_matrix_add\\T12_matrix_add.hx"
			{
				#line 20 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T12_matrix_add\\T12_matrix_add.hx"
				int _g = 0;
				#line 20 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T12_matrix_add\\T12_matrix_add.hx"
				int _g1 = n;
				#line 20 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T12_matrix_add\\T12_matrix_add.hx"
				while (( _g < _g1 )) {
					#line 20 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T12_matrix_add\\T12_matrix_add.hx"
					int i = _g++;
					{
						#line 21 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T12_matrix_add\\T12_matrix_add.hx"
						int _g2 = 0;
						#line 21 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T12_matrix_add\\T12_matrix_add.hx"
						int _g3 = n;
						#line 21 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T12_matrix_add\\T12_matrix_add.hx"
						while (( _g2 < _g3 )) {
							#line 21 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T12_matrix_add\\T12_matrix_add.hx"
							int j = _g2++;
							a[( ( i * n ) + j )] = ( i + j );
							#line 23 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T12_matrix_add\\T12_matrix_add.hx"
							b[( ( i * n ) + j )] = ( i - j );
						}
						
					}
					
				}
				
			}
			
			#line 27 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T12_matrix_add\\T12_matrix_add.hx"
			{
				#line 27 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T12_matrix_add\\T12_matrix_add.hx"
				int _g4 = 0;
				#line 27 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T12_matrix_add\\T12_matrix_add.hx"
				int _g5 = n;
				#line 27 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T12_matrix_add\\T12_matrix_add.hx"
				while (( _g4 < _g5 )) {
					#line 27 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T12_matrix_add\\T12_matrix_add.hx"
					int i1 = _g4++;
					{
						#line 28 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T12_matrix_add\\T12_matrix_add.hx"
						int _g6 = 0;
						#line 28 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T12_matrix_add\\T12_matrix_add.hx"
						int _g7 = n;
						#line 28 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T12_matrix_add\\T12_matrix_add.hx"
						while (( _g6 < _g7 )) {
							#line 28 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T12_matrix_add\\T12_matrix_add.hx"
							int j1 = _g6++;
							c[( ( i1 * n ) + j1 )] = ( a[( ( i1 * n ) + j1 )] + b[( ( i1 * n ) + j1 )] );
						}
						
					}
					
				}
				
			}
			
			#line 33 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T12_matrix_add\\T12_matrix_add.hx"
			long total = ((long) (0) );
			{
				#line 34 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T12_matrix_add\\T12_matrix_add.hx"
				int _g8 = 0;
				#line 34 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T12_matrix_add\\T12_matrix_add.hx"
				int _g9 = elems;
				#line 34 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T12_matrix_add\\T12_matrix_add.hx"
				while (( _g8 < _g9 )) {
					#line 34 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T12_matrix_add\\T12_matrix_add.hx"
					int k = _g8++;
					total = ((long) (( ((long) (total) ) + ((long) (c[k]) ) )) );
				}
				
			}
			
			#line 38 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T12_matrix_add\\T12_matrix_add.hx"
			double t1 = global::Sys.time();
			global::Out.err(global::haxe.lang.Runtime.concat(global::haxe.lang.Runtime.concat("TIME_MS=", global::haxe.lang.Runtime.toString(( (( t1 - t0 )) * 1000.0 ))), "\n"));
			#line 40 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T12_matrix_add\\T12_matrix_add.hx"
			global::Out.line(total);
		}
		#line default
	}
	
	
}


