
#ifndef _C1_an1_
#define _C1_an1_

#ifdef __cplusplus
extern "C" {
#endif

extern EIF_REFERENCE F1_5(EIF_REFERENCE);
extern EIF_BOOLEAN F1_7(EIF_REFERENCE, EIF_REFERENCE);
extern EIF_BOOLEAN F1_8(EIF_REFERENCE, EIF_REFERENCE);
extern EIF_REFERENCE F1_14(EIF_REFERENCE);
extern void F1_15(EIF_REFERENCE, EIF_REFERENCE);
extern void F1_16(EIF_REFERENCE, EIF_REFERENCE);
extern void F1_23(EIF_REFERENCE);
RTOSHF (EIF_REFERENCE,24)
static EIF_REFERENCE F1_24_body(EIF_REFERENCE);
extern EIF_REFERENCE F1_24(EIF_REFERENCE);
extern void F1_29(EIF_REFERENCE);
extern void F1_30(EIF_REFERENCE);
extern void F1_31(EIF_REFERENCE);
extern EIF_POINTER F1_33(EIF_REFERENCE);
extern void EIF_Minit1(void);
extern void F25_452(EIF_REFERENCE);
extern void F75_1074(EIF_REFERENCE, EIF_REFERENCE);
extern void F780_4848(EIF_REFERENCE, EIF_REFERENCE);
extern EIF_REFERENCE F775_4662(EIF_REFERENCE);
extern void F778_4735(EIF_REFERENCE, EIF_REFERENCE);
extern char *(*R2637[])();
extern char *(*R2255[])();

#ifdef __cplusplus
}
#endif

#endif
