
#ifndef _C1_co18_
#define _C1_co18_

#ifdef __cplusplus
extern "C" {
#endif

RTOSHF (EIF_REFERENCE,534)
static EIF_REFERENCE F30_534_body(EIF_REFERENCE);
extern EIF_REFERENCE F30_534(EIF_REFERENCE);
RTOSHF (EIF_REFERENCE,535)
static EIF_REFERENCE F30_535_body(EIF_REFERENCE);
extern EIF_REFERENCE F30_535(EIF_REFERENCE);
RTOSHF (EIF_REFERENCE,536)
static EIF_REFERENCE F30_536_body(EIF_REFERENCE);
extern EIF_REFERENCE F30_536(EIF_REFERENCE);
RTOSHF (EIF_REFERENCE,537)
static EIF_REFERENCE F30_537_body(EIF_REFERENCE);
extern EIF_REFERENCE F30_537(EIF_REFERENCE);
extern void EIF_Minit18(void);
extern void F598_3039(EIF_REFERENCE, EIF_INTEGER_32);
extern EIF_REFERENCE F3_42(EIF_REFERENCE);
extern EIF_REFERENCE F3_47(EIF_REFERENCE);
extern void F594_2973(EIF_REFERENCE, EIF_REFERENCE, EIF_REFERENCE);
extern EIF_REFERENCE F3_44(EIF_REFERENCE);
extern EIF_REFERENCE F3_46(EIF_REFERENCE);
extern EIF_REFERENCE F3_49(EIF_REFERENCE);
extern EIF_REFERENCE F783_5048(EIF_REFERENCE);
extern EIF_REFERENCE F3_43(EIF_REFERENCE);
extern EIF_REFERENCE F3_45(EIF_REFERENCE);
extern EIF_REFERENCE F3_48(EIF_REFERENCE);
RTOSHF(EIF_REFERENCE,42)
RTOSHF(EIF_REFERENCE,43)
RTOSHF(EIF_REFERENCE,44)
RTOSHF(EIF_REFERENCE,46)
RTOSHF(EIF_REFERENCE,45)
RTOSHF(EIF_REFERENCE,47)
RTOSHF(EIF_REFERENCE,48)
RTOSHF(EIF_REFERENCE,49)

#ifdef __cplusplus
}
#endif

#endif
