
#ifndef _C1_sy2_
#define _C1_sy2_

#ifdef __cplusplus
extern "C" {
#endif

RTOSHF (EIF_REFERENCE,36)
static EIF_REFERENCE F2_36_body(EIF_REFERENCE);
extern EIF_REFERENCE F2_36(EIF_REFERENCE);
RTOSHF (EIF_REFERENCE,37)
static EIF_REFERENCE F2_37_body(EIF_REFERENCE);
extern EIF_REFERENCE F2_37(EIF_REFERENCE);
RTOSHF (EIF_REFERENCE,39)
static EIF_REFERENCE F2_39_body(EIF_REFERENCE);
extern EIF_REFERENCE F2_39(EIF_REFERENCE);
RTOSHF (EIF_REFERENCE,41)
static EIF_REFERENCE F2_41_body(EIF_REFERENCE);
extern EIF_REFERENCE F2_41(EIF_REFERENCE);
extern void EIF_Minit2(void);
extern void F4_50(EIF_REFERENCE, EIF_REFERENCE);
extern EIF_REFERENCE F35_583(EIF_REFERENCE);
extern EIF_REFERENCE F3_43(EIF_REFERENCE);
extern EIF_REFERENCE F3_45(EIF_REFERENCE);
RTOSHF(EIF_REFERENCE,43)
RTOSHF(EIF_REFERENCE,45)

#ifdef __cplusplus
}
#endif

#endif
