<?php
/**
 * Generated by Haxe 4.3.7
 */

use \php\Boot;

class T03_func_sum {
	/**
	 * @return void
	 */
	public static function main () {
		#T03_func_sum.hx:15: characters 9-37
		$t0 = microtime(true);
		#T03_func_sum.hx:16: characters 9-23
		$value = 0;
		#T03_func_sum.hx:18: characters 19-23
		$_g = 0;
		#T03_func_sum.hx:18: lines 18-20
		while ($_g < 100000000) {
			#T03_func_sum.hx:18: characters 19-32
			$i = $_g++;
			#T03_func_sum.hx:19: characters 13-42
			$value = \AddOne::add_one($value);
		}
		#T03_func_sum.hx:22: characters 9-37
		$t1 = microtime(true);
		#T03_func_sum.hx:23: characters 9-58
		\Out::err("TIME_MS=" . (($t1 - $t0) * 1000.0) . "\x0A");
		#T03_func_sum.hx:24: characters 9-24
		\Out::line($value);
	}
}

Boot::registerClass(T03_func_sum::class, 'T03_func_sum');
