// Generated by Haxe 4.3.7

#pragma warning disable 109, 114, 219, 429, 168, 162
namespace haxe.io {
	public class Output : global::haxe.lang.HxObject {
		
		public Output(global::haxe.lang.EmptyObject empty) {
		}
		
		
		public Output() {
			#line 31 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\io\\Output.hx"
			global::haxe.io.Output.__hx_ctor_haxe_io_Output(this);
		}
		#line default
		
		protected static void __hx_ctor_haxe_io_Output(global::haxe.io.Output __hx_this) {
		}
		
		
		public virtual void writeByte(int c) {
			unchecked {
				#line 47 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\io\\Output.hx"
				throw new global::haxe.exceptions.NotImplementedException(default(string), default(global::haxe.Exception), ((object) (new global::haxe.lang.DynamicObject(new int[]{302979532, 1547539107, 1648581351}, new object[]{"writeByte", "haxe.io.Output", "haxe/io/Output.hx"}, new int[]{1981972957}, new double[]{((double) (47) )})) ));
			}
			#line default
		}
		
		
		public virtual int writeBytes(global::haxe.io.Bytes s, int pos, int len) {
			#line 59 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\io\\Output.hx"
			if (( ( ( pos < 0 ) || ( len < 0 ) ) || ( ( pos + len ) > s.length ) )) {
				#line 60 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\io\\Output.hx"
				throw ((global::System.Exception) (global::haxe.Exception.thrown(global::haxe.io.Error.OutsideBounds)) );
			}
			
			#line 62 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\io\\Output.hx"
			byte[] b = s.b;
			int k = len;
			#line 64 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\io\\Output.hx"
			while (( k > 0 )) {
				#line 74 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\io\\Output.hx"
				this.writeByte(((int) (b[pos]) ));
				#line 76 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\io\\Output.hx"
				 ++ pos;
				 -- k;
			}
			
			#line 79 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\io\\Output.hx"
			return len;
		}
		#line default
		
		public virtual void writeFullBytes(global::haxe.io.Bytes s, int pos, int len) {
			#line 121 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\io\\Output.hx"
			while (( len > 0 )) {
				#line 122 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\io\\Output.hx"
				int k = this.writeBytes(s, pos, len);
				pos += k;
				#line 124 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\io\\Output.hx"
				len -= k;
			}
			
		}
		#line default
		
		public virtual void writeString(string s, global::haxe.io.Encoding encoding) {
			#line 282 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\io\\Output.hx"
			global::haxe.io.Bytes b = global::haxe.io.Bytes.ofString(s, encoding);
			#line 284 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\io\\Output.hx"
			this.writeFullBytes(b, 0, b.length);
		}
		#line default
		
		public override object __hx_getField(string field, int hash, bool throwErrors, bool isCheck, bool handleProperties) {
			unchecked {
				#line 31 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\io\\Output.hx"
				switch (hash) {
					case 640252688:
					{
						#line 31 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\io\\Output.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "writeString", 640252688)) );
					}
					
					
					case 610723709:
					{
						#line 31 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\io\\Output.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "writeFullBytes", 610723709)) );
					}
					
					
					case 1381630732:
					{
						#line 31 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\io\\Output.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "writeBytes", 1381630732)) );
					}
					
					
					case 1238832007:
					{
						#line 31 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\io\\Output.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "writeByte", 1238832007)) );
					}
					
					
					default:
					{
						#line 31 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\io\\Output.hx"
						return base.__hx_getField(field, hash, throwErrors, isCheck, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override object __hx_invokeField(string field, int hash, object[] dynargs) {
			unchecked {
				#line 31 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\io\\Output.hx"
				switch (hash) {
					case 640252688:
					{
						#line 31 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\io\\Output.hx"
						this.writeString(global::haxe.lang.Runtime.toString(dynargs[0]), ((global::haxe.io.Encoding) (( (( dynargs.Length > 1 )) ? (dynargs[1]) : (null) )) ));
						#line 31 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\io\\Output.hx"
						break;
					}
					
					
					case 610723709:
					{
						#line 31 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\io\\Output.hx"
						this.writeFullBytes(((global::haxe.io.Bytes) (dynargs[0]) ), ((int) (global::haxe.lang.Runtime.toInt(dynargs[1])) ), ((int) (global::haxe.lang.Runtime.toInt(dynargs[2])) ));
						#line 31 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\io\\Output.hx"
						break;
					}
					
					
					case 1381630732:
					{
						#line 31 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\io\\Output.hx"
						return this.writeBytes(((global::haxe.io.Bytes) (dynargs[0]) ), ((int) (global::haxe.lang.Runtime.toInt(dynargs[1])) ), ((int) (global::haxe.lang.Runtime.toInt(dynargs[2])) ));
					}
					
					
					case 1238832007:
					{
						#line 31 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\io\\Output.hx"
						this.writeByte(((int) (global::haxe.lang.Runtime.toInt(dynargs[0])) ));
						#line 31 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\io\\Output.hx"
						break;
					}
					
					
					default:
					{
						#line 31 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\io\\Output.hx"
						return base.__hx_invokeField(field, hash, dynargs);
					}
					
				}
				
				#line 31 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\io\\Output.hx"
				return null;
			}
			#line default
		}
		
		
	}
}


