
#ifndef _C1_an1_
#define _C1_an1_

#ifdef __cplusplus
extern "C" {
#endif

extern EIF_REFERENCE F1_5(EIF_REFERENCE);
extern EIF_BOOLEAN F1_7(EIF_REFERENCE, EIF_REFERENCE);
extern EIF_BOOLEAN F1_8(EIF_REFERENCE, EIF_REFERENCE);
extern EIF_REFERENCE F1_14(EIF_REFERENCE);
extern void F1_15(EIF_REFERENCE, EIF_REFERENCE);
extern void F1_16(EIF_REFERENCE, EIF_REFERENCE);
extern void F1_23(EIF_REFERENCE);
RTOSHF (EIF_REFERENCE,24)
static EIF_REFERENCE F1_24_body(EIF_REFERENCE);
extern EIF_REFERENCE F1_24(EIF_REFERENCE);
extern void F1_29(EIF_REFERENCE);
extern void F1_30(EIF_REFERENCE);
extern void F1_31(EIF_REFERENCE);
extern EIF_POINTER F1_33(EIF_REFERENCE);
extern void EIF_Minit1(void);
extern void F820_5030(EIF_REFERENCE, EIF_REFERENCE);
extern void F77_1090(EIF_REFERENCE, EIF_REFERENCE);
extern void F818_4917(EIF_REFERENCE, EIF_REFERENCE);
extern EIF_REFERENCE F812_4678(EIF_REFERENCE);
extern void F27_459(EIF_REFERENCE);
extern char *(*R2271[])();
extern char *(*R2653[])();

#ifdef __cplusplus
}
#endif

#endif
