
#ifndef _C1_ch6_
#define _C1_ch6_

#ifdef __cplusplus
extern "C" {
#endif

extern void F6_70(EIF_REFERENCE);
extern EIF_CHARACTER_32 F6_83(EIF_REFERENCE, EIF_CHARACTER_32);
RTOSHF (EIF_REFERENCE,95)
static EIF_REFERENCE F6_95_body(EIF_REFERENCE);
extern EIF_REFERENCE F6_95(EIF_REFERENCE);
RTOSHF (EIF_REFERENCE,96)
static EIF_REFERENCE F6_96_body(EIF_REFERENCE);
extern EIF_REFERENCE F6_96(EIF_REFERENCE);
RTOSHF (EIF_REFERENCE,97)
static EIF_REFERENCE F6_97_body(EIF_REFERENCE);
extern EIF_REFERENCE F6_97(EIF_REFERENCE);
RTOSHF (EIF_REFERENCE,98)
static EIF_REFERENCE F6_98_body(EIF_REFERENCE);
extern EIF_REFERENCE F6_98(EIF_REFERENCE);
RTOSHF (EIF_REFERENCE,99)
static EIF_REFERENCE F6_99_body(EIF_REFERENCE);
extern EIF_REFERENCE F6_99(EIF_REFERENCE);
RTOSHF (EIF_REFERENCE,100)
static EIF_REFERENCE F6_100_body(EIF_REFERENCE);
extern EIF_REFERENCE F6_100(EIF_REFERENCE);
RTOSHF (EIF_REFERENCE,101)
static EIF_REFERENCE F6_101_body(EIF_REFERENCE);
extern EIF_REFERENCE F6_101(EIF_REFERENCE);
RTOSHF (EIF_REFERENCE,102)
static EIF_REFERENCE F6_102_body(EIF_REFERENCE);
extern EIF_REFERENCE F6_102(EIF_REFERENCE);
RTOSHF (EIF_REFERENCE,103)
static EIF_REFERENCE F6_103_body(EIF_REFERENCE);
extern EIF_REFERENCE F6_103(EIF_REFERENCE);
RTOSHF (EIF_REFERENCE,104)
static EIF_REFERENCE F6_104_body(EIF_REFERENCE);
extern EIF_REFERENCE F6_104(EIF_REFERENCE);
RTOSHF (EIF_REFERENCE,105)
static EIF_REFERENCE F6_105_body(EIF_REFERENCE);
extern EIF_REFERENCE F6_105(EIF_REFERENCE);
RTOSHF (EIF_REFERENCE,106)
static EIF_REFERENCE F6_106_body(EIF_REFERENCE);
extern EIF_REFERENCE F6_106(EIF_REFERENCE);
RTOSHF (EIF_REFERENCE,107)
static EIF_REFERENCE F6_107_body(EIF_REFERENCE);
extern EIF_REFERENCE F6_107(EIF_REFERENCE);
RTOSHF (EIF_REFERENCE,108)
static EIF_REFERENCE F6_108_body(EIF_REFERENCE);
extern EIF_REFERENCE F6_108(EIF_REFERENCE);
RTOSHF (EIF_REFERENCE,109)
static EIF_REFERENCE F6_109_body(EIF_REFERENCE);
extern EIF_REFERENCE F6_109(EIF_REFERENCE);
RTOSHF (EIF_REFERENCE,110)
static EIF_REFERENCE F6_110_body(EIF_REFERENCE);
extern EIF_REFERENCE F6_110(EIF_REFERENCE);
extern void EIF_Minit6(void);
extern EIF_REFERENCE F652_3181(EIF_REFERENCE);
extern EIF_REFERENCE F645_3181(EIF_REFERENCE);

#ifdef __cplusplus
}
#endif

#endif
