
#ifndef _C1_co20_
#define _C1_co20_

#ifdef __cplusplus
extern "C" {
#endif

RTOSHF (EIF_REFERENCE,562)
static EIF_REFERENCE F33_562_body(EIF_REFERENCE);
extern EIF_REFERENCE F33_562(EIF_REFERENCE);
RTOSHF (EIF_REFERENCE,563)
static EIF_REFERENCE F33_563_body(EIF_REFERENCE);
extern EIF_REFERENCE F33_563(EIF_REFERENCE);
RTOSHF (EIF_REFERENCE,564)
static EIF_REFERENCE F33_564_body(EIF_REFERENCE);
extern EIF_REFERENCE F33_564(EIF_REFERENCE);
RTOSHF (EIF_REFERENCE,565)
static EIF_REFERENCE F33_565_body(EIF_REFERENCE);
extern EIF_REFERENCE F33_565(EIF_REFERENCE);
extern void EIF_Minit20(void);
extern EIF_REFERENCE F2_37(EIF_REFERENCE);
extern EIF_REFERENCE F2_41(EIF_REFERENCE);
extern void F634_3055(EIF_REFERENCE, EIF_INTEGER_32);
extern void F630_2989(EIF_REFERENCE, EIF_REFERENCE, EIF_REFERENCE);
extern EIF_REFERENCE F2_36(EIF_REFERENCE);
extern EIF_REFERENCE F2_39(EIF_REFERENCE);
extern EIF_REFERENCE F2_40(EIF_REFERENCE);
extern EIF_REFERENCE F817_4897(EIF_REFERENCE);
extern EIF_REFERENCE F2_35(EIF_REFERENCE);
extern EIF_REFERENCE F2_38(EIF_REFERENCE);
extern EIF_REFERENCE F2_42(EIF_REFERENCE);
RTOSHF(EIF_REFERENCE,35)
RTOSHF(EIF_REFERENCE,36)
RTOSHF(EIF_REFERENCE,37)
RTOSHF(EIF_REFERENCE,39)
RTOSHF(EIF_REFERENCE,38)
RTOSHF(EIF_REFERENCE,40)
RTOSHF(EIF_REFERENCE,41)
RTOSHF(EIF_REFERENCE,42)

#ifdef __cplusplus
}
#endif

#endif
