// Generated by Haxe 4.3.7

#pragma warning disable 109, 114, 219, 429, 168, 162
namespace sys.io {
	public class File : global::haxe.lang.HxObject {
		
		public File(global::haxe.lang.EmptyObject empty) {
		}
		
		
		public File() {
			#line 26 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\cs\\_std\\sys\\io\\File.hx"
			global::sys.io.File.__hx_ctor_sys_io_File(this);
		}
		#line default
		
		protected static void __hx_ctor_sys_io_File(global::sys.io.File __hx_this) {
		}
		
		
		public static global::sys.io.FileOutput write(string path, global::haxe.lang.Null<bool> binary) {
			#line 62 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\cs\\_std\\sys\\io\\File.hx"
			bool binary1 = ( ( ! (binary.hasValue) ) ? (true) : ((binary).@value) );
			#line 66 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\cs\\_std\\sys\\io\\File.hx"
			global::System.IO.FileStream stream = new global::System.IO.FileStream(((string) (path) ), ((global::System.IO.FileMode) (global::System.IO.FileMode.Create) ), ((global::System.IO.FileAccess) (global::System.IO.FileAccess.Write) ), ((global::System.IO.FileShare) (global::System.IO.FileShare.ReadWrite) ));
			#line 68 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\cs\\_std\\sys\\io\\File.hx"
			return new global::sys.io.FileOutput(((global::System.IO.FileStream) (stream) ));
		}
		#line default
		
	}
}


