// Generated by Haxe 4.3.7

#pragma warning disable 109, 114, 219, 429, 168, 162
public class T02_switch_case : global::haxe.lang.HxObject {
	
	public static void Main(){
		global::cs.Boot.init();
		{
			global::T02_switch_case.main();
			global::sys.thread._Thread.Thread_Impl_.processEvents();
		}
		;
	}
	public T02_switch_case(global::haxe.lang.EmptyObject empty) {
	}
	
	
	public T02_switch_case() {
		#line 7 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T02_switch_case\\T02_switch_case.hx"
		global::T02_switch_case.__hx_ctor__T02_switch_case(this);
	}
	#line default
	
	protected static void __hx_ctor__T02_switch_case(global::T02_switch_case __hx_this) {
	}
	
	
	public static void main() {
		unchecked {
			#line 10 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T02_switch_case\\T02_switch_case.hx"
			double t0 = global::Sys.time();
			long acc = ((long) (0) );
			#line 13 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T02_switch_case\\T02_switch_case.hx"
			{
				#line 13 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T02_switch_case\\T02_switch_case.hx"
				int _g = 0;
				#line 13 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T02_switch_case\\T02_switch_case.hx"
				while (( _g < 100000000 )) {
					#line 13 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T02_switch_case\\T02_switch_case.hx"
					int i = _g++;
					switch (( i % 4 )) {
						case 0:
						{
							#line 16 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T02_switch_case\\T02_switch_case.hx"
							acc = ((long) (( ((long) (acc) ) + ((long) (1) ) )) );
							#line 16 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T02_switch_case\\T02_switch_case.hx"
							break;
						}
						
						
						case 1:
						{
							#line 18 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T02_switch_case\\T02_switch_case.hx"
							acc = ((long) (( ((long) (acc) ) + ((long) (i) ) )) );
							#line 18 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T02_switch_case\\T02_switch_case.hx"
							break;
						}
						
						
						case 2:
						{
							#line 20 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T02_switch_case\\T02_switch_case.hx"
							acc = ((long) (( ((long) (acc) ) + ((long) (( 2 * i )) ) )) );
							#line 20 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T02_switch_case\\T02_switch_case.hx"
							break;
						}
						
						
						case 3:
						{
							#line 22 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T02_switch_case\\T02_switch_case.hx"
							acc = ((long) (( ((long) (acc) ) + ((long) (( 3 * i )) ) )) );
							#line 22 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T02_switch_case\\T02_switch_case.hx"
							break;
						}
						
						
					}
					
				}
				
			}
			
			#line 26 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T02_switch_case\\T02_switch_case.hx"
			double t1 = global::Sys.time();
			global::Out.err(global::haxe.lang.Runtime.concat(global::haxe.lang.Runtime.concat("TIME_MS=", global::haxe.lang.Runtime.toString(( (( t1 - t0 )) * 1000.0 ))), "\n"));
			#line 28 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T02_switch_case\\T02_switch_case.hx"
			global::Out.line(acc);
		}
		#line default
	}
	
	
}


