
#ifndef _C1_sy3_
#define _C1_sy3_

#ifdef __cplusplus
extern "C" {
#endif

RTOSHF (EIF_REFERENCE,44)
static EIF_REFERENCE F3_44_body(EIF_REFERENCE);
extern EIF_REFERENCE F3_44(EIF_REFERENCE);
RTOSHF (EIF_REFERENCE,45)
static EIF_REFERENCE F3_45_body(EIF_REFERENCE);
extern EIF_REFERENCE F3_45(EIF_REFERENCE);
RTOSHF (EIF_REFERENCE,47)
static EIF_REFERENCE F3_47_body(EIF_REFERENCE);
extern EIF_REFERENCE F3_47(EIF_REFERENCE);
RTOSHF (EIF_REFERENCE,49)
static EIF_REFERENCE F3_49_body(EIF_REFERENCE);
extern EIF_REFERENCE F3_49(EIF_REFERENCE);
extern void EIF_Minit3(void);
extern EIF_REFERENCE F2_36(EIF_REFERENCE);
extern EIF_REFERENCE F35_581(EIF_REFERENCE);
extern void F4_50(EIF_REFERENCE, EIF_REFERENCE);
extern EIF_REFERENCE F2_38(EIF_REFERENCE);
RTOSHF(EIF_REFERENCE,36)
RTOSHF(EIF_REFERENCE,38)

#ifdef __cplusplus
}
#endif

#endif
