<?php
/**
 * Generated by Haxe 4.3.7
 */

use \haxe\_Int64\___Int64;
use \php\Boot;
use \haxe\_Int32\Int32_Impl_;

class T02_switch_case {
	/**
	 * @return void
	 */
	public static function main () {
		#T02_switch_case.hx:10: characters 9-37
		$t0 = microtime(true);
		#T02_switch_case.hx:11: characters 9-39
		$acc = new ___Int64(0, 0);
		#T02_switch_case.hx:13: characters 19-23
		$_g = 0;
		#T02_switch_case.hx:13: lines 13-24
		while ($_g < 100000000) {
			#T02_switch_case.hx:13: characters 19-32
			$i = $_g++;
			#T02_switch_case.hx:14: characters 21-26
			$__hx__switch = ($i % 4);
			if ($__hx__switch === 0) {
				#T02_switch_case.hx:16: characters 21-29
				$b_high = 0;
				$b_low = 1;
				$high = (($acc->high + $b_high) << Int32_Impl_::$extraBits) >> Int32_Impl_::$extraBits;
				$low = (($acc->low + $b_low) << Int32_Impl_::$extraBits) >> Int32_Impl_::$extraBits;
				if (Int32_Impl_::ucompare($low, $acc->low) < 0) {
					$ret = $high++;
					#D:\Users\pedro.cardoso\stupidspeed\tools\haxe\std/haxe/Int64.hx:264: characters 4-8
					$high = ($high << Int32_Impl_::$extraBits) >> Int32_Impl_::$extraBits;
				}
				#T02_switch_case.hx:16: characters 21-29
				$acc = new ___Int64($high, $low);
			} else if ($__hx__switch === 1) {
				#T02_switch_case.hx:18: characters 21-29
				$b_high1 = $i >> 31;
				$b_low1 = $i;
				$high1 = (($acc->high + $b_high1) << Int32_Impl_::$extraBits) >> Int32_Impl_::$extraBits;
				$low1 = (($acc->low + $b_low1) << Int32_Impl_::$extraBits) >> Int32_Impl_::$extraBits;
				if (Int32_Impl_::ucompare($low1, $acc->low) < 0) {
					$ret1 = $high1++;
					#D:\Users\pedro.cardoso\stupidspeed\tools\haxe\std/haxe/Int64.hx:264: characters 4-8
					$high1 = ($high1 << Int32_Impl_::$extraBits) >> Int32_Impl_::$extraBits;
				}
				#T02_switch_case.hx:18: characters 21-29
				$acc = new ___Int64($high1, $low1);
			} else if ($__hx__switch === 2) {
				#T02_switch_case.hx:20: characters 21-33
				$x = 2 * $i;
				$b_high2 = $x >> 31;
				$b_low2 = $x;
				$high2 = (($acc->high + $b_high2) << Int32_Impl_::$extraBits) >> Int32_Impl_::$extraBits;
				$low2 = (($acc->low + $b_low2) << Int32_Impl_::$extraBits) >> Int32_Impl_::$extraBits;
				if (Int32_Impl_::ucompare($low2, $acc->low) < 0) {
					$ret2 = $high2++;
					#D:\Users\pedro.cardoso\stupidspeed\tools\haxe\std/haxe/Int64.hx:264: characters 4-8
					$high2 = ($high2 << Int32_Impl_::$extraBits) >> Int32_Impl_::$extraBits;
				}
				#T02_switch_case.hx:20: characters 21-33
				$acc = new ___Int64($high2, $low2);
			} else if ($__hx__switch === 3) {
				#T02_switch_case.hx:22: characters 21-33
				$x1 = 3 * $i;
				$b_high3 = $x1 >> 31;
				$b_low3 = $x1;
				$high3 = (($acc->high + $b_high3) << Int32_Impl_::$extraBits) >> Int32_Impl_::$extraBits;
				$low3 = (($acc->low + $b_low3) << Int32_Impl_::$extraBits) >> Int32_Impl_::$extraBits;
				if (Int32_Impl_::ucompare($low3, $acc->low) < 0) {
					$ret3 = $high3++;
					#D:\Users\pedro.cardoso\stupidspeed\tools\haxe\std/haxe/Int64.hx:264: characters 4-8
					$high3 = ($high3 << Int32_Impl_::$extraBits) >> Int32_Impl_::$extraBits;
				}
				#T02_switch_case.hx:22: characters 21-33
				$acc = new ___Int64($high3, $low3);
			}
		}
		#T02_switch_case.hx:26: characters 9-37
		$t1 = microtime(true);
		#T02_switch_case.hx:27: characters 9-58
		\Out::err("TIME_MS=" . (($t1 - $t0) * 1000.0) . "\x0A");
		#T02_switch_case.hx:28: characters 9-22
		\Out::line($acc);
	}
}

Boot::registerClass(T02_switch_case::class, 'T02_switch_case');
