
#ifndef _C1_co18_
#define _C1_co18_

#ifdef __cplusplus
extern "C" {
#endif

RTOSHF (EIF_REFERENCE,532)
static EIF_REFERENCE F30_532_body(EIF_REFERENCE);
extern EIF_REFERENCE F30_532(EIF_REFERENCE);
RTOSHF (EIF_REFERENCE,533)
static EIF_REFERENCE F30_533_body(EIF_REFERENCE);
extern EIF_REFERENCE F30_533(EIF_REFERENCE);
RTOSHF (EIF_REFERENCE,534)
static EIF_REFERENCE F30_534_body(EIF_REFERENCE);
extern EIF_REFERENCE F30_534(EIF_REFERENCE);
RTOSHF (EIF_REFERENCE,535)
static EIF_REFERENCE F30_535_body(EIF_REFERENCE);
extern EIF_REFERENCE F30_535(EIF_REFERENCE);
extern void EIF_Minit18(void);
extern EIF_REFERENCE F4_60(EIF_REFERENCE);
extern void F598_3037(EIF_REFERENCE, EIF_INTEGER_32);
extern void F594_2971(EIF_REFERENCE, EIF_REFERENCE, EIF_REFERENCE);
extern EIF_REFERENCE F4_58(EIF_REFERENCE);
extern EIF_REFERENCE F783_5046(EIF_REFERENCE);
extern EIF_REFERENCE F4_62(EIF_REFERENCE);
extern EIF_REFERENCE F4_57(EIF_REFERENCE);
extern EIF_REFERENCE F4_61(EIF_REFERENCE);
extern EIF_REFERENCE F4_64(EIF_REFERENCE);
extern EIF_REFERENCE F4_63(EIF_REFERENCE);
extern EIF_REFERENCE F4_59(EIF_REFERENCE);
RTOSHF(EIF_REFERENCE,57)
RTOSHF(EIF_REFERENCE,58)
RTOSHF(EIF_REFERENCE,59)
RTOSHF(EIF_REFERENCE,61)
RTOSHF(EIF_REFERENCE,60)
RTOSHF(EIF_REFERENCE,62)
RTOSHF(EIF_REFERENCE,63)
RTOSHF(EIF_REFERENCE,64)

#ifdef __cplusplus
}
#endif

#endif
