<?php
/**
 * Generated by Haxe 4.3.7
 */

use \php\Boot;
use \sys\io\File;
use \haxe\io\Bytes;

class T15_file_write {
	/**
	 * @var int
	 */
	const CHUNK = 1048576;
	/**
	 * @var int
	 */
	const REPEATS = 50;

	/**
	 * @return void
	 */
	public static function main () {
		#T15_file_write.hx:19: characters 9-37
		$t0 = microtime(true);
		#T15_file_write.hx:39: characters 9-46
		$buf = Bytes::alloc(1048576);
		#T15_file_write.hx:40: characters 19-23
		$_g = 0;
		#T15_file_write.hx:40: lines 40-42
		while ($_g < 1048576) {
			#T15_file_write.hx:40: characters 19-28
			$i = $_g++;
			#T15_file_write.hx:41: characters 13-32
			$buf->b->s[$i] = chr($i % 256);
		}
		#T15_file_write.hx:44: characters 9-52
		$f = File::write("out.bin", true);
		#T15_file_write.hx:46: characters 9-25
		$written = 0;
		#T15_file_write.hx:47: characters 19-23
		$_g = 0;
		#T15_file_write.hx:47: lines 47-49
		while ($_g < 50) {
			#T15_file_write.hx:47: characters 19-30
			$i = $_g++;
			#T15_file_write.hx:48: characters 13-51
			$written += $f->writeBytes($buf, 0, 1048576);
		}
		#T15_file_write.hx:51: characters 9-18
		$f->flush();
		#T15_file_write.hx:52: characters 9-18
		$f->close();
		#T15_file_write.hx:55: characters 9-37
		$t1 = microtime(true);
		#T15_file_write.hx:56: characters 9-58
		\Out::err("TIME_MS=" . (($t1 - $t0) * 1000.0) . "\x0A");
		#T15_file_write.hx:57: characters 9-26
		\Out::line($written);
	}
}

Boot::registerClass(T15_file_write::class, 'T15_file_write');
