// Generated by Haxe 4.3.7

#pragma warning disable 109, 114, 219, 429, 168, 162
public class T09_fib_recursive : global::haxe.lang.HxObject {
	
	public static void Main(){
		global::cs.Boot.init();
		{
			global::T09_fib_recursive.main();
			global::sys.thread._Thread.Thread_Impl_.processEvents();
		}
		;
	}
	public T09_fib_recursive(global::haxe.lang.EmptyObject empty) {
	}
	
	
	public T09_fib_recursive() {
		#line 6 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T09_fib_recursive\\T09_fib_recursive.hx"
		global::T09_fib_recursive.__hx_ctor__T09_fib_recursive(this);
	}
	#line default
	
	protected static void __hx_ctor__T09_fib_recursive(global::T09_fib_recursive __hx_this) {
	}
	
	
	public static int fib(int n) {
		unchecked {
			#line 8 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T09_fib_recursive\\T09_fib_recursive.hx"
			if (( n < 2 )) {
				#line 9 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T09_fib_recursive\\T09_fib_recursive.hx"
				return n;
			}
			
			#line 11 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T09_fib_recursive\\T09_fib_recursive.hx"
			return ( global::T09_fib_recursive.fib(( n - 1 )) + global::T09_fib_recursive.fib(( n - 2 )) );
		}
		#line default
	}
	
	
	public static void main() {
		unchecked {
			#line 16 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T09_fib_recursive\\T09_fib_recursive.hx"
			double t0 = global::Sys.time();
			int answer = global::T09_fib_recursive.fib(40);
			#line 18 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T09_fib_recursive\\T09_fib_recursive.hx"
			double t1 = global::Sys.time();
			global::Out.err(global::haxe.lang.Runtime.concat(global::haxe.lang.Runtime.concat("TIME_MS=", global::haxe.lang.Runtime.toString(( (( t1 - t0 )) * 1000.0 ))), "\n"));
			#line 20 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T09_fib_recursive\\T09_fib_recursive.hx"
			global::Out.line(answer);
		}
		#line default
	}
	
	
}


