
#ifndef _C1_co19_
#define _C1_co19_

#ifdef __cplusplus
extern "C" {
#endif

RTOSHF (EIF_REFERENCE,544)
static EIF_REFERENCE F31_544_body(EIF_REFERENCE);
extern EIF_REFERENCE F31_544(EIF_REFERENCE);
RTOSHF (EIF_REFERENCE,545)
static EIF_REFERENCE F31_545_body(EIF_REFERENCE);
extern EIF_REFERENCE F31_545(EIF_REFERENCE);
RTOSHF (EIF_REFERENCE,546)
static EIF_REFERENCE F31_546_body(EIF_REFERENCE);
extern EIF_REFERENCE F31_546(EIF_REFERENCE);
RTOSHF (EIF_REFERENCE,547)
static EIF_REFERENCE F31_547_body(EIF_REFERENCE);
extern EIF_REFERENCE F31_547(EIF_REFERENCE);
extern void EIF_Minit19(void);
extern EIF_REFERENCE F4_60(EIF_REFERENCE);
extern void F598_3037(EIF_REFERENCE, EIF_INTEGER_32);
extern void F594_2971(EIF_REFERENCE, EIF_REFERENCE, EIF_REFERENCE);
extern EIF_REFERENCE F4_58(EIF_REFERENCE);
extern EIF_REFERENCE F783_5046(EIF_REFERENCE);
extern EIF_REFERENCE F4_62(EIF_REFERENCE);
extern EIF_REFERENCE F4_57(EIF_REFERENCE);
extern EIF_REFERENCE F4_61(EIF_REFERENCE);
extern EIF_REFERENCE F4_64(EIF_REFERENCE);
extern EIF_REFERENCE F4_63(EIF_REFERENCE);
extern EIF_REFERENCE F4_59(EIF_REFERENCE);
RTOSHF(EIF_REFERENCE,57)
RTOSHF(EIF_REFERENCE,58)
RTOSHF(EIF_REFERENCE,59)
RTOSHF(EIF_REFERENCE,61)
RTOSHF(EIF_REFERENCE,60)
RTOSHF(EIF_REFERENCE,62)
RTOSHF(EIF_REFERENCE,63)
RTOSHF(EIF_REFERENCE,64)

#ifdef __cplusplus
}
#endif

#endif
