
#ifndef _C1_co4_
#define _C1_co4_

#ifdef __cplusplus
extern "C" {
#endif
RTOSHF (EIF_REFERENCE, 57)


extern EIF_REFERENCE F4_57(EIF_REFERENCE);RTOSHF (EIF_REFERENCE, 58)


extern EIF_REFERENCE F4_58(EIF_REFERENCE);RTOSHF (EIF_REFERENCE, 59)


extern EIF_REFERENCE F4_59(EIF_REFERENCE);RTOSHF (EIF_REFERENCE, 60)


extern EIF_REFERENCE F4_60(EIF_REFERENCE);RTOSHF (EIF_REFERENCE, 61)


extern EIF_REFERENCE F4_61(EIF_REFERENCE);RTOSHF (EIF_REFERENCE, 62)


extern EIF_REFERENCE F4_62(EIF_REFERENCE);RTOSHF (EIF_REFERENCE, 63)


extern EIF_REFERENCE F4_63(EIF_REFERENCE);RTOSHF (EIF_REFERENCE, 64)


extern EIF_REFERENCE F4_64(EIF_REFERENCE);
extern void EIF_Minit4(void);

#ifdef __cplusplus
}
#endif

#endif
