// Generated by Haxe 4.3.7

#pragma warning disable 109, 114, 219, 429, 168, 162
namespace haxe {
	public class EntryPoint : global::haxe.lang.HxObject {
		
		public EntryPoint(global::haxe.lang.EmptyObject empty) {
		}
		
		
		public EntryPoint() {
			#line 35 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\EntryPoint.hx"
			global::haxe.EntryPoint.__hx_ctor_haxe_EntryPoint(this);
		}
		#line default
		
		protected static void __hx_ctor_haxe_EntryPoint(global::haxe.EntryPoint __hx_this) {
		}
		
		
		public static void run() {
		}
		
		
	}
}


