// Generated by Haxe 4.3.7

#pragma warning disable 109, 114, 219, 429, 168, 162
public class T01_branches : global::haxe.lang.HxObject {
	
	public static void Main(){
		global::cs.Boot.init();
		{
			global::T01_branches.main();
			global::sys.thread._Thread.Thread_Impl_.processEvents();
		}
		;
	}
	public T01_branches(global::haxe.lang.EmptyObject empty) {
	}
	
	
	public T01_branches() {
		#line 11 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T01_branches\\T01_branches.hx"
		global::T01_branches.__hx_ctor__T01_branches(this);
	}
	#line default
	
	protected static void __hx_ctor__T01_branches(global::T01_branches __hx_this) {
	}
	
	
	public static void main() {
		unchecked {
			#line 14 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T01_branches\\T01_branches.hx"
			double t0 = global::Sys.time();
			int a = 0;
			#line 16 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T01_branches\\T01_branches.hx"
			int b = 0;
			int c = 0;
			#line 18 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T01_branches\\T01_branches.hx"
			int d = 0;
			#line 20 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T01_branches\\T01_branches.hx"
			{
				#line 20 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T01_branches\\T01_branches.hx"
				int _g = 0;
				#line 20 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T01_branches\\T01_branches.hx"
				while (( _g < 100000000 )) {
					#line 20 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T01_branches\\T01_branches.hx"
					int i = _g++;
					if (( ( i % 3 ) == 0 )) {
						#line 22 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T01_branches\\T01_branches.hx"
						 ++ a;
					}
					else if (( ( i % 5 ) == 0 )) {
						#line 24 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T01_branches\\T01_branches.hx"
						 ++ b;
					}
					else if (( ( i % 7 ) == 0 )) {
						#line 26 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T01_branches\\T01_branches.hx"
						 ++ c;
					}
					else {
						#line 28 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T01_branches\\T01_branches.hx"
						 ++ d;
					}
					
				}
				
			}
			
			#line 32 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T01_branches\\T01_branches.hx"
			double t1 = global::Sys.time();
			global::Out.err(global::haxe.lang.Runtime.concat(global::haxe.lang.Runtime.concat("TIME_MS=", global::haxe.lang.Runtime.toString(( (( t1 - t0 )) * 1000.0 ))), "\n"));
			#line 34 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T01_branches\\T01_branches.hx"
			global::Out.line(global::haxe.lang.Runtime.concat(global::haxe.lang.Runtime.concat(global::haxe.lang.Runtime.concat(global::haxe.lang.Runtime.concat(global::haxe.lang.Runtime.concat(global::haxe.lang.Runtime.concat(global::haxe.lang.Runtime.concat("", global::haxe.lang.Runtime.toString(a)), " "), global::haxe.lang.Runtime.toString(b)), " "), global::haxe.lang.Runtime.toString(c)), " "), global::haxe.lang.Runtime.toString(d)));
		}
		#line default
	}
	
	
}


