<?php
/**
 * Generated by Haxe 4.3.7
 */

use \haxe\_Int64\___Int64;
use \php\Boot;
use \haxe\_Int32\Int32_Impl_;

class T12_matrix_add {
	/**
	 * @return void
	 */
	public static function main () {
		#T12_matrix_add.hx:12: characters 9-37
		$t0 = microtime(true);
		#T12_matrix_add.hx:13: characters 9-22
		$n = 1000;
		#T12_matrix_add.hx:14: characters 9-27
		$elems = $n * $n;
		#T12_matrix_add.hx:16: characters 9-34
		$a = new \Array_hx();
		#T12_matrix_add.hx:17: characters 9-34
		$b = new \Array_hx();
		#T12_matrix_add.hx:18: characters 9-34
		$c = new \Array_hx();
		#T12_matrix_add.hx:20: characters 19-23
		$_g = 0;
		#T12_matrix_add.hx:20: characters 23-24
		$_g1 = $n;
		#T12_matrix_add.hx:20: lines 20-25
		while ($_g < $_g1) {
			#T12_matrix_add.hx:20: characters 19-24
			$i = $_g++;
			#T12_matrix_add.hx:21: characters 23-27
			$_g2 = 0;
			#T12_matrix_add.hx:21: characters 27-28
			$_g3 = $n;
			#T12_matrix_add.hx:21: lines 21-24
			while ($_g2 < $_g3) {
				#T12_matrix_add.hx:21: characters 23-28
				$j = $_g2++;
				#T12_matrix_add.hx:22: characters 17-29
				$a->offsetSet($i * $n + $j, $i + $j);
				#T12_matrix_add.hx:23: characters 17-29
				$b->offsetSet($i * $n + $j, $i - $j);
			}
		}
		#T12_matrix_add.hx:27: characters 19-23
		$_g = 0;
		#T12_matrix_add.hx:27: characters 23-24
		$_g1 = $n;
		#T12_matrix_add.hx:27: lines 27-31
		while ($_g < $_g1) {
			#T12_matrix_add.hx:27: characters 19-24
			$i = $_g++;
			#T12_matrix_add.hx:28: characters 23-27
			$_g2 = 0;
			#T12_matrix_add.hx:28: characters 27-28
			$_g3 = $n;
			#T12_matrix_add.hx:28: lines 28-30
			while ($_g2 < $_g3) {
				#T12_matrix_add.hx:28: characters 23-28
				$j = $_g2++;
				#T12_matrix_add.hx:29: characters 17-29
				$c->offsetSet($i * $n + $j, ($a->arr[$i * $n + $j] ?? null) + ($b->arr[$i * $n + $j] ?? null));
			}
		}
		#T12_matrix_add.hx:33: characters 9-41
		$total = new ___Int64(0, 0);
		#T12_matrix_add.hx:34: characters 19-23
		$_g = 0;
		#T12_matrix_add.hx:34: characters 23-28
		$_g1 = $elems;
		#T12_matrix_add.hx:34: lines 34-36
		while ($_g < $_g1) {
			#T12_matrix_add.hx:34: characters 19-28
			$k = $_g++;
			#T12_matrix_add.hx:35: characters 13-26
			$x = ($c->arr[$k] ?? null);
			$b_high = $x >> 31;
			$b_low = $x;
			$high = (($total->high + $b_high) << Int32_Impl_::$extraBits) >> Int32_Impl_::$extraBits;
			$low = (($total->low + $b_low) << Int32_Impl_::$extraBits) >> Int32_Impl_::$extraBits;
			if (Int32_Impl_::ucompare($low, $total->low) < 0) {
				$ret = $high++;
				#D:\Users\pedro.cardoso\stupidspeed\tools\haxe\std/haxe/Int64.hx:264: characters 4-8
				$high = ($high << Int32_Impl_::$extraBits) >> Int32_Impl_::$extraBits;
			}
			#T12_matrix_add.hx:35: characters 13-26
			$total = new ___Int64($high, $low);
		}
		#T12_matrix_add.hx:38: characters 9-37
		$t1 = microtime(true);
		#T12_matrix_add.hx:39: characters 9-58
		\Out::err("TIME_MS=" . (($t1 - $t0) * 1000.0) . "\x0A");
		#T12_matrix_add.hx:40: characters 9-24
		\Out::line($total);
	}
}

Boot::registerClass(T12_matrix_add::class, 'T12_matrix_add');
