
#ifndef _C1_co18_
#define _C1_co18_

#ifdef __cplusplus
extern "C" {
#endif

RTOSHF (EIF_REFERENCE,532)
static EIF_REFERENCE F31_532_body(EIF_REFERENCE);
extern EIF_REFERENCE F31_532(EIF_REFERENCE);
RTOSHF (EIF_REFERENCE,533)
static EIF_REFERENCE F31_533_body(EIF_REFERENCE);
extern EIF_REFERENCE F31_533(EIF_REFERENCE);
RTOSHF (EIF_REFERENCE,534)
static EIF_REFERENCE F31_534_body(EIF_REFERENCE);
extern EIF_REFERENCE F31_534(EIF_REFERENCE);
RTOSHF (EIF_REFERENCE,535)
static EIF_REFERENCE F31_535_body(EIF_REFERENCE);
extern EIF_REFERENCE F31_535(EIF_REFERENCE);
extern void EIF_Minit18(void);
extern EIF_REFERENCE F2_37(EIF_REFERENCE);
extern void F633_3037(EIF_REFERENCE, EIF_INTEGER_32);
extern EIF_REFERENCE F819_5046(EIF_REFERENCE);
extern EIF_REFERENCE F2_41(EIF_REFERENCE);
extern EIF_REFERENCE F2_36(EIF_REFERENCE);
extern EIF_REFERENCE F2_39(EIF_REFERENCE);
extern EIF_REFERENCE F2_40(EIF_REFERENCE);
extern EIF_REFERENCE F2_35(EIF_REFERENCE);
extern EIF_REFERENCE F2_38(EIF_REFERENCE);
extern EIF_REFERENCE F2_42(EIF_REFERENCE);
extern void F629_2971(EIF_REFERENCE, EIF_REFERENCE, EIF_REFERENCE);
RTOSHF(EIF_REFERENCE,35)
RTOSHF(EIF_REFERENCE,36)
RTOSHF(EIF_REFERENCE,37)
RTOSHF(EIF_REFERENCE,39)
RTOSHF(EIF_REFERENCE,38)
RTOSHF(EIF_REFERENCE,40)
RTOSHF(EIF_REFERENCE,41)
RTOSHF(EIF_REFERENCE,42)

#ifdef __cplusplus
}
#endif

#endif
