
#ifndef _C1_co2_
#define _C1_co2_

#ifdef __cplusplus
extern "C" {
#endif
RTOSHF (EIF_REFERENCE, 35)


extern EIF_REFERENCE F2_35(EIF_REFERENCE);RTOSHF (EIF_REFERENCE, 36)


extern EIF_REFERENCE F2_36(EIF_REFERENCE);RTOSHF (EIF_REFERENCE, 37)


extern EIF_REFERENCE F2_37(EIF_REFERENCE);RTOSHF (EIF_REFERENCE, 38)


extern EIF_REFERENCE F2_38(EIF_REFERENCE);RTOSHF (EIF_REFERENCE, 39)


extern EIF_REFERENCE F2_39(EIF_REFERENCE);RTOSHF (EIF_REFERENCE, 40)


extern EIF_REFERENCE F2_40(EIF_REFERENCE);RTOSHF (EIF_REFERENCE, 41)


extern EIF_REFERENCE F2_41(EIF_REFERENCE);RTOSHF (EIF_REFERENCE, 42)


extern EIF_REFERENCE F2_42(EIF_REFERENCE);
extern void EIF_Minit2(void);

#ifdef __cplusplus
}
#endif

#endif
