
#ifndef _C1_co18_
#define _C1_co18_

#ifdef __cplusplus
extern "C" {
#endif

static EIF_REFERENCE F30_532_body(EIF_REFERENCE);
extern EIF_REFERENCE F30_532(EIF_REFERENCE);
static EIF_REFERENCE F30_533_body(EIF_REFERENCE);
extern EIF_REFERENCE F30_533(EIF_REFERENCE);
static EIF_REFERENCE F30_534_body(EIF_REFERENCE);
extern EIF_REFERENCE F30_534(EIF_REFERENCE);
static EIF_REFERENCE F30_535_body(EIF_REFERENCE);
extern EIF_REFERENCE F30_535(EIF_REFERENCE);
extern void EIF_Minit18(void);
extern EIF_REFERENCE F4_60(EIF_REFERENCE);
extern EIF_REFERENCE F4_63(EIF_REFERENCE);
extern EIF_REFERENCE F4_58(EIF_REFERENCE);
extern void F601_3026(EIF_REFERENCE, EIF_REFERENCE, EIF_REFERENCE);
extern EIF_REFERENCE F4_62(EIF_REFERENCE);
extern EIF_REFERENCE F787_4934(EIF_REFERENCE);
extern EIF_REFERENCE F4_57(EIF_REFERENCE);
extern EIF_REFERENCE F4_61(EIF_REFERENCE);
extern EIF_REFERENCE F4_64(EIF_REFERENCE);
extern void F605_3092(EIF_REFERENCE, EIF_INTEGER_32);
extern EIF_REFERENCE F4_59(EIF_REFERENCE);

#ifdef __cplusplus
}
#endif

#endif
