/*
 * Generated by ISE 25.12.9.8922 - win64
 */

#include "eif_eiffel.h"
#include "eif_project.h"
#include "egc_include.h"
#include "eoffsets.h"

#ifdef __cplusplus
extern "C" {
#endif
extern void F1_23();
extern EIF_REFERENCE F1_14();
extern void F817_4898();
extern void F817_4902();
extern void F814_4731();
extern void F814_4736();
extern void F546_2654();
extern void F44_669();
extern EIF_REFERENCE F44_656();
extern EIF_BOOLEAN F44_668();
extern EIF_BOOLEAN F44_676();
extern void F44_678();
extern void F44_679();
extern void F44_680();
extern void egc_routine_tables_init (void);

long *eif_area_table = (long *)0;
long *eif_lower_table = (long *)0;
extern char *(*R2[])();
extern char *(*R6[])();
extern char *(*R3[])();

extern char *(*R4[])();

extern char *(*R5[])();



extern void egc_init_plug (void); 
void egc_init_plug (void)
{
	egc_prof_enabled = (EIF_INTEGER) 0;
	egc_correct_mismatch = (void (*)(EIF_REFERENCE)) F1_23;
	egc_twin = (EIF_REFERENCE (*)(EIF_REFERENCE)) F1_14;
	egc_strmake = (void (*)(EIF_REFERENCE, EIF_INTEGER)) F817_4898;
	egc_immstr8make_from_c_byte_array = (void (*)(EIF_REFERENCE, EIF_POINTER, EIF_INTEGER)) F817_4902;
	egc_str32make = (void (*)(EIF_REFERENCE, EIF_INTEGER)) F814_4731;
	egc_immstr32make_from_c_byte_array = (void (*)(EIF_REFERENCE, EIF_POINTER, EIF_INTEGER)) F814_4736;
	egc_arrmake = (void (*)(EIF_REFERENCE, EIF_INTEGER, EIF_INTEGER)) F546_2654;
	egc_str_count_offset = + _LNGOFF_1_1_0_2_;
	egc_str_hash_offset = + _LNGOFF_1_1_0_0_;
	egc_str32_count_offset = + _LNGOFF_1_1_0_2_;
	egc_str32_hash_offset = + _LNGOFF_1_1_0_0_;
	egc_is_scoop_capable = 0;
	egc_set_exception_data = (void (*)(EIF_REFERENCE, EIF_INTEGER, EIF_BOOLEAN, EIF_INTEGER, EIF_INTEGER, EIF_REFERENCE, EIF_REFERENCE, EIF_REFERENCE, EIF_REFERENCE, EIF_REFERENCE, EIF_REFERENCE, EIF_INTEGER, EIF_BOOLEAN)) F44_669;
	egc_set_last_exception = (void (*)(EIF_REFERENCE, EIF_REFERENCE)) F44_668;
	egc_last_exception = (EIF_REFERENCE (*)(EIF_REFERENCE)) F44_656;
	egc_is_code_ignored = (EIF_BOOLEAN (*)(EIF_REFERENCE, EIF_INTEGER)) F44_676;
	egc_once_raise = (void (*)(EIF_REFERENCE, EIF_REFERENCE)) F44_678;
	egc_init_exception_manager = (void (*)(EIF_REFERENCE)) F44_679;
	egc_free_preallocated_trace = (void (*)(EIF_REFERENCE)) F44_680;

	egc_str_dtype = 818;

	egc_immstr8_dtype = 817;

	egc_str32_dtype = 815;

	egc_immstr32_dtype = 814;
	egc_arr_dtype = 545;
	egc_tup_dtype = 732;
	egc_disp_rout_id = 1084;
	egc_copy_rout_id = 18;
	egc_is_equal_rout_id = 11;

	egc_sp_char = 0x0281;
	egc_sp_wchar = 0x0280;
	egc_sp_bool = 0x0288;
	egc_sp_uint8 = 0x0282;
	egc_sp_uint16 = 0x0283;
	egc_sp_uint32 = 0x028A;
	egc_sp_uint64 = 0x0289;
	egc_sp_int8 = 0xFFFF;
	egc_sp_int16 = 0xFFFF;
	egc_sp_int32 = 0x0287;
	egc_sp_int64 = 0x028B;
	egc_sp_real32 = 0x0285;
	egc_sp_real64 = 0x0286;
	egc_sp_pointer = 0x0284;
	egc_sp_ref = 0x027F;

	egc_uint8_dtype = 768;
	egc_uint16_dtype = 765;
	egc_uint32_dtype = 762;
	egc_uint64_dtype = 759;
	egc_int8_dtype = 756;
	egc_int16_dtype = 753;
	egc_int32_dtype = 750;
	egc_int64_dtype = 747;
	egc_bool_dtype = 744;
	egc_real32_dtype = 771;
	egc_char_dtype = 741;
	egc_wchar_dtype = 738;
	egc_real64_dtype = 735;
	egc_point_dtype = 804;

	egc_exception_dtype = 76;
	egc_except_emnger_dtype = 43;

	egc_ce_type = egc_ce_type_init;

	egc_ce_exp_type = egc_ce_exp_type_init;
	egc_fsystem = egc_fsystem_init;
	egc_system_mod_init = egc_system_mod_init_init;
	egc_partab = egc_partab_init;
	egc_partab_size = egc_partab_size_init;
	exception_stack_managed = (EIF_BOOLEAN) 0;
	egc_ecreate = (void (**)(EIF_REFERENCE, EIF_REFERENCE)) R2;
	egc_exp_create = (void (**)(EIF_REFERENCE)) R6;
	egc_edispose = (void (**)(void)) R3;
	egc_copy = (void (**)(EIF_REFERENCE, EIF_REFERENCE)) R4;
	egc_is_equal = (EIF_BOOLEAN (**)(EIF_REFERENCE, EIF_REFERENCE)) R5;
	egc_ce_rname = egc_ce_rname_init;
	egc_fnbref = egc_fnbref_init;
	egc_fsize = egc_fsize_init;

	egc_system_name = "prog";
	egc_system_location = "C:\\stupidspeed\\exec\\eiffel\\EIFGENs\\t13_matrix_mul\\F_code";
	egc_compiler_tag = 39;
	egc_project_version = 1791175617;
	egc_has_old_special_semantic = 0;
	scount = 833;

	egc_rcount = 1;
	egc_ridx = 0;
	egc_rlist = (char**) eif_malloc (sizeof(char*)*egc_rcount);
	egc_rcdt = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rlist[0] = "T13_MATRIX_MUL.make";
	egc_rcdt[0] = 0;
	
	
	egc_platform_level = 0x00000D00;
	egc_routine_tables_init();
}

void egc_rcdt_init (void)
{
	if (egc_rcdt[0] == 0) {
		egc_rcdt[0] = 27; /* T13_MATRIX_MUL */
	}
}

#ifdef __cplusplus
}
#endif
