// Generated by Haxe 4.3.7

#pragma warning disable 109, 114, 219, 429, 168, 162
namespace haxe.io {
	public class Bytes : global::haxe.lang.HxObject {
		
		public Bytes(global::haxe.lang.EmptyObject empty) {
		}
		
		
		public Bytes(int length, byte[] b) {
			#line 34 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\io\\Bytes.hx"
			global::haxe.io.Bytes.__hx_ctor_haxe_io_Bytes(this, length, b);
		}
		#line default
		
		protected static void __hx_ctor_haxe_io_Bytes(global::haxe.io.Bytes __hx_this, int length, byte[] b) {
			#line 35 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\io\\Bytes.hx"
			__hx_this.length = length;
			__hx_this.b = b;
		}
		#line default
		
		public static global::haxe.io.Bytes alloc(int length) {
			#line 562 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\io\\Bytes.hx"
			return new global::haxe.io.Bytes(((int) (length) ), ((byte[]) (new byte[length]) ));
		}
		#line default
		
		public static global::haxe.io.Bytes ofString(string s, global::haxe.io.Encoding encoding) {
			unchecked {
				#line 595 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\io\\Bytes.hx"
				byte[] b = null;
				#line 595 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\io\\Bytes.hx"
				if (( encoding == null )) {
					#line 595 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\io\\Bytes.hx"
					b = global::System.Text.Encoding.UTF8.GetBytes(((string) (s) ));
				}
				else {
					#line 595 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\io\\Bytes.hx"
					switch (encoding._hx_index) {
						case 0:
						{
							#line 595 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\io\\Bytes.hx"
							b = global::System.Text.Encoding.UTF8.GetBytes(((string) (s) ));
							#line 595 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\io\\Bytes.hx"
							break;
						}
						
						
						case 1:
						{
							#line 595 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\io\\Bytes.hx"
							b = global::System.Text.Encoding.Unicode.GetBytes(((string) (s) ));
							#line 595 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\io\\Bytes.hx"
							break;
						}
						
						
					}
					
				}
				
				#line 601 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\io\\Bytes.hx"
				return new global::haxe.io.Bytes(((int) (( b as global::System.Array ).Length) ), ((byte[]) (b) ));
			}
			#line default
		}
		
		
		public int length;
		
		public byte[] b;
		
		public override double __hx_setField_f(string field, int hash, double @value, bool handleProperties) {
			unchecked {
				#line 29 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\io\\Bytes.hx"
				switch (hash) {
					case 520590566:
					{
						#line 29 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\io\\Bytes.hx"
						this.length = ((int) (@value) );
						#line 29 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\io\\Bytes.hx"
						return @value;
					}
					
					
					default:
					{
						#line 29 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\io\\Bytes.hx"
						return base.__hx_setField_f(field, hash, @value, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override object __hx_setField(string field, int hash, object @value, bool handleProperties) {
			unchecked {
				#line 29 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\io\\Bytes.hx"
				switch (hash) {
					case 98:
					{
						#line 29 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\io\\Bytes.hx"
						this.b = ((byte[]) (@value) );
						#line 29 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\io\\Bytes.hx"
						return @value;
					}
					
					
					case 520590566:
					{
						#line 29 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\io\\Bytes.hx"
						this.length = ((int) (global::haxe.lang.Runtime.toInt(@value)) );
						#line 29 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\io\\Bytes.hx"
						return @value;
					}
					
					
					default:
					{
						#line 29 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\io\\Bytes.hx"
						return base.__hx_setField(field, hash, @value, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override object __hx_getField(string field, int hash, bool throwErrors, bool isCheck, bool handleProperties) {
			unchecked {
				#line 29 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\io\\Bytes.hx"
				switch (hash) {
					case 98:
					{
						#line 29 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\io\\Bytes.hx"
						return this.b;
					}
					
					
					case 520590566:
					{
						#line 29 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\io\\Bytes.hx"
						return this.length;
					}
					
					
					default:
					{
						#line 29 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\io\\Bytes.hx"
						return base.__hx_getField(field, hash, throwErrors, isCheck, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override double __hx_getField_f(string field, int hash, bool throwErrors, bool handleProperties) {
			unchecked {
				#line 29 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\io\\Bytes.hx"
				switch (hash) {
					case 520590566:
					{
						#line 29 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\io\\Bytes.hx"
						return ((double) (this.length) );
					}
					
					
					default:
					{
						#line 29 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\io\\Bytes.hx"
						return base.__hx_getField_f(field, hash, throwErrors, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override void __hx_getFields(global::Array<string> baseArr) {
			#line 29 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\io\\Bytes.hx"
			baseArr.push("b");
			#line 29 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\io\\Bytes.hx"
			baseArr.push("length");
			#line 29 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\io\\Bytes.hx"
			base.__hx_getFields(baseArr);
		}
		#line default
		
	}
}


