// Generated by Haxe 4.3.7

#pragma warning disable 109, 114, 219, 429, 168, 162
public class Sys : global::haxe.lang.HxObject {
	
	public Sys(global::haxe.lang.EmptyObject empty) {
	}
	
	
	public Sys() {
		#line 28 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\cs\\_std\\Sys.hx"
		global::Sys.__hx_ctor__Sys(this);
	}
	#line default
	
	protected static void __hx_ctor__Sys(global::Sys __hx_this) {
	}
	
	
	public static readonly long epochTicks = new global::System.DateTime(((int) (1970) ), ((int) (1) ), ((int) (1) )).Ticks;
	
	public static double time() {
		#line 128 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\cs\\_std\\Sys.hx"
		return ( ((double) (((long) (( ((long) (global::System.DateTime.UtcNow.Ticks) ) - ((long) (global::Sys.epochTicks) ) )) )) ) / ((double) (global::System.TimeSpan.TicksPerSecond) ) );
	}
	#line default
	
}


