// Generated by Haxe 4.3.7
(function ($global) { "use strict";
function $extend(from, fields) {
	var proto = Object.create(from);
	for (var name in fields) proto[name] = fields[name];
	if( fields.toString !== Object.prototype.toString ) proto.toString = fields.toString;
	return proto;
}
var HxOverrides = function() { };
HxOverrides.__name__ = true;
HxOverrides.now = function() {
	return Date.now();
};
Math.__name__ = true;
var Out = function() { };
Out.__name__ = true;
Out.line = function(v) {
	var s = ((v) instanceof haxe__$Int64__$_$_$Int64) ? haxe_Int64.toString(v) : Std.string(v);
	process.stdout.write(s + "\n");
};
Out.err = function(s) {
	process.stderr.write(s);
};
var Std = function() { };
Std.__name__ = true;
Std.string = function(s) {
	return js_Boot.__string_rec(s,"");
};
var Job = function(t) {
	this.t = t;
	this.acc = new haxe__$Int64__$_$_$Int64(0,0);
};
Job.__name__ = true;
var T11_$parallel_$sum = function() { };
T11_$parallel_$sum.__name__ = true;
T11_$parallel_$sum.work_range = function(t) {
	var acc = new haxe__$Int64__$_$_$Int64(0,0);
	var lo = t * 25000000;
	var hi = lo + 25000000;
	var _g = lo;
	var _g1 = hi;
	while(_g < _g1) {
		var i = _g++;
		switch(i % 4) {
		case 0:
			var b_high = 0;
			var b_low = 1;
			var high = acc.high + b_high | 0;
			var low = acc.low + b_low | 0;
			if(haxe_Int32.ucompare(low,acc.low) < 0) {
				var ret = high++;
				high = high | 0;
			}
			acc = new haxe__$Int64__$_$_$Int64(high,low);
			break;
		case 1:
			var b_high1 = i >> 31;
			var b_low1 = i;
			var high1 = acc.high + b_high1 | 0;
			var low1 = acc.low + b_low1 | 0;
			if(haxe_Int32.ucompare(low1,acc.low) < 0) {
				var ret1 = high1++;
				high1 = high1 | 0;
			}
			acc = new haxe__$Int64__$_$_$Int64(high1,low1);
			break;
		case 2:
			var x = 2 * i;
			var b_high2 = x >> 31;
			var b_low2 = x;
			var high2 = acc.high + b_high2 | 0;
			var low2 = acc.low + b_low2 | 0;
			if(haxe_Int32.ucompare(low2,acc.low) < 0) {
				var ret2 = high2++;
				high2 = high2 | 0;
			}
			acc = new haxe__$Int64__$_$_$Int64(high2,low2);
			break;
		case 3:
			var x1 = 3 * i;
			var b_high3 = x1 >> 31;
			var b_low3 = x1;
			var high3 = acc.high + b_high3 | 0;
			var low3 = acc.low + b_low3 | 0;
			if(haxe_Int32.ucompare(low3,acc.low) < 0) {
				var ret3 = high3++;
				high3 = high3 | 0;
			}
			acc = new haxe__$Int64__$_$_$Int64(high3,low3);
			break;
		}
	}
	return acc;
};
T11_$parallel_$sum.main = function() {
	var wt = require('worker_threads');
	if(wt.isMainThread == false) {
		var wd = wt.workerData;
		var acc = T11_$parallel_$sum.work_range(wd.t);
		var w32 = new Int32Array(wd.sab);
		w32[1 + wd.t * 2] = acc.low;
		w32[2 + wd.t * 2] = acc.high;
		Atomics.add(w32, 0, 1);
		Atomics.notify(w32, 0);
		return;
	}
	var t0 = HxOverrides.now() / 1000;
	var sab = new SharedArrayBuffer(36);
	var w32 = new Int32Array(sab);
	var workers = [];
	workers.push(new (require('worker_threads').Worker)(__filename, { workerData : { t : 0, sab : sab}}));
	workers.push(new (require('worker_threads').Worker)(__filename, { workerData : { t : 1, sab : sab}}));
	workers.push(new (require('worker_threads').Worker)(__filename, { workerData : { t : 2, sab : sab}}));
	workers.push(new (require('worker_threads').Worker)(__filename, { workerData : { t : 3, sab : sab}}));
	var joined = 0;
	while(joined < 4) {
		Atomics.wait(w32, 0, joined, 1000);
		joined = w32[0];
	}
	if(workers.length != 4) {
		throw haxe_Exception.thrown("worker_threads: expected " + 4 + " workers");
	}
	var total = new haxe__$Int64__$_$_$Int64(0,0);
	var b_high = w32[2];
	var b_low = w32[1];
	var high = total.high + b_high | 0;
	var low = total.low + b_low | 0;
	if(haxe_Int32.ucompare(low,total.low) < 0) {
		var ret = high++;
		high = high | 0;
	}
	total = new haxe__$Int64__$_$_$Int64(high,low);
	var b_high = w32[4];
	var b_low = w32[3];
	var high = total.high + b_high | 0;
	var low = total.low + b_low | 0;
	if(haxe_Int32.ucompare(low,total.low) < 0) {
		var ret = high++;
		high = high | 0;
	}
	total = new haxe__$Int64__$_$_$Int64(high,low);
	var b_high = w32[6];
	var b_low = w32[5];
	var high = total.high + b_high | 0;
	var low = total.low + b_low | 0;
	if(haxe_Int32.ucompare(low,total.low) < 0) {
		var ret = high++;
		high = high | 0;
	}
	total = new haxe__$Int64__$_$_$Int64(high,low);
	var b_high = w32[8];
	var b_low = w32[7];
	var high = total.high + b_high | 0;
	var low = total.low + b_low | 0;
	if(haxe_Int32.ucompare(low,total.low) < 0) {
		var ret = high++;
		high = high | 0;
	}
	total = new haxe__$Int64__$_$_$Int64(high,low);
	var t1 = HxOverrides.now() / 1000;
	Out.err("TIME_MS=" + (t1 - t0) * 1000.0 + "\n");
	Out.line(total);
};
var haxe_Exception = function(message,previous,native) {
	Error.call(this,message);
	this.message = message;
	this.__previousException = previous;
	this.__nativeException = native != null ? native : this;
};
haxe_Exception.__name__ = true;
haxe_Exception.thrown = function(value) {
	if(((value) instanceof haxe_Exception)) {
		return value.get_native();
	} else if(((value) instanceof Error)) {
		return value;
	} else {
		var e = new haxe_ValueException(value);
		return e;
	}
};
haxe_Exception.__super__ = Error;
haxe_Exception.prototype = $extend(Error.prototype,{
	get_native: function() {
		return this.__nativeException;
	}
});
var haxe_Int32 = {};
haxe_Int32.ucompare = function(a,b) {
	if(a < 0) {
		if(b < 0) {
			return ~b - ~a | 0;
		} else {
			return 1;
		}
	}
	if(b < 0) {
		return -1;
	} else {
		return a - b | 0;
	}
};
var haxe_Int64 = {};
haxe_Int64.toString = function(this1) {
	var i = this1;
	var b_high = 0;
	var b_low = 0;
	if(i.high == b_high && i.low == b_low) {
		return "0";
	}
	var str = "";
	var neg = false;
	if(i.high < 0) {
		neg = true;
	}
	var ten = new haxe__$Int64__$_$_$Int64(0,10);
	while(true) {
		var b_high = 0;
		var b_low = 0;
		if(!(i.high != b_high || i.low != b_low)) {
			break;
		}
		var r = haxe_Int64.divMod(i,ten);
		if(r.modulus.high < 0) {
			var x = r.modulus;
			var high = ~x.high;
			var low = ~x.low + 1 | 0;
			if(low == 0) {
				var ret = high++;
				high = high | 0;
			}
			var this_high = high;
			var this_low = low;
			str = this_low + str;
			var x1 = r.quotient;
			var high1 = ~x1.high;
			var low1 = ~x1.low + 1 | 0;
			if(low1 == 0) {
				var ret1 = high1++;
				high1 = high1 | 0;
			}
			i = new haxe__$Int64__$_$_$Int64(high1,low1);
		} else {
			str = r.modulus.low + str;
			i = r.quotient;
		}
	}
	if(neg) {
		str = "-" + str;
	}
	return str;
};
haxe_Int64.divMod = function(dividend,divisor) {
	if(divisor.high == 0) {
		switch(divisor.low) {
		case 0:
			throw haxe_Exception.thrown("divide by zero");
		case 1:
			return { quotient : new haxe__$Int64__$_$_$Int64(dividend.high,dividend.low), modulus : new haxe__$Int64__$_$_$Int64(0,0)};
		}
	}
	var divSign = dividend.high < 0 != divisor.high < 0;
	var modulus;
	if(dividend.high < 0) {
		var high = ~dividend.high;
		var low = ~dividend.low + 1 | 0;
		if(low == 0) {
			var ret = high++;
			high = high | 0;
		}
		modulus = new haxe__$Int64__$_$_$Int64(high,low);
	} else {
		modulus = new haxe__$Int64__$_$_$Int64(dividend.high,dividend.low);
	}
	if(divisor.high < 0) {
		var high = ~divisor.high;
		var low = ~divisor.low + 1 | 0;
		if(low == 0) {
			var ret = high++;
			high = high | 0;
		}
		divisor = new haxe__$Int64__$_$_$Int64(high,low);
	}
	var quotient = new haxe__$Int64__$_$_$Int64(0,0);
	var mask = new haxe__$Int64__$_$_$Int64(0,1);
	while(!(divisor.high < 0)) {
		var v = haxe_Int32.ucompare(divisor.high,modulus.high);
		var cmp = v != 0 ? v : haxe_Int32.ucompare(divisor.low,modulus.low);
		var b = 1;
		b &= 63;
		divisor = b == 0 ? new haxe__$Int64__$_$_$Int64(divisor.high,divisor.low) : b < 32 ? new haxe__$Int64__$_$_$Int64(divisor.high << b | divisor.low >>> 32 - b,divisor.low << b) : new haxe__$Int64__$_$_$Int64(divisor.low << b - 32,0);
		var b1 = 1;
		b1 &= 63;
		mask = b1 == 0 ? new haxe__$Int64__$_$_$Int64(mask.high,mask.low) : b1 < 32 ? new haxe__$Int64__$_$_$Int64(mask.high << b1 | mask.low >>> 32 - b1,mask.low << b1) : new haxe__$Int64__$_$_$Int64(mask.low << b1 - 32,0);
		if(cmp >= 0) {
			break;
		}
	}
	while(true) {
		var b_high = 0;
		var b_low = 0;
		if(!(mask.high != b_high || mask.low != b_low)) {
			break;
		}
		var v = haxe_Int32.ucompare(modulus.high,divisor.high);
		if((v != 0 ? v : haxe_Int32.ucompare(modulus.low,divisor.low)) >= 0) {
			quotient = new haxe__$Int64__$_$_$Int64(quotient.high | mask.high,quotient.low | mask.low);
			var high = modulus.high - divisor.high | 0;
			var low = modulus.low - divisor.low | 0;
			if(haxe_Int32.ucompare(modulus.low,divisor.low) < 0) {
				var ret = high--;
				high = high | 0;
			}
			modulus = new haxe__$Int64__$_$_$Int64(high,low);
		}
		var b = 1;
		b &= 63;
		mask = b == 0 ? new haxe__$Int64__$_$_$Int64(mask.high,mask.low) : b < 32 ? new haxe__$Int64__$_$_$Int64(mask.high >>> b,mask.high << 32 - b | mask.low >>> b) : new haxe__$Int64__$_$_$Int64(0,mask.high >>> b - 32);
		var b1 = 1;
		b1 &= 63;
		divisor = b1 == 0 ? new haxe__$Int64__$_$_$Int64(divisor.high,divisor.low) : b1 < 32 ? new haxe__$Int64__$_$_$Int64(divisor.high >>> b1,divisor.high << 32 - b1 | divisor.low >>> b1) : new haxe__$Int64__$_$_$Int64(0,divisor.high >>> b1 - 32);
	}
	if(divSign) {
		var high = ~quotient.high;
		var low = ~quotient.low + 1 | 0;
		if(low == 0) {
			var ret = high++;
			high = high | 0;
		}
		quotient = new haxe__$Int64__$_$_$Int64(high,low);
	}
	if(dividend.high < 0) {
		var high = ~modulus.high;
		var low = ~modulus.low + 1 | 0;
		if(low == 0) {
			var ret = high++;
			high = high | 0;
		}
		modulus = new haxe__$Int64__$_$_$Int64(high,low);
	}
	return { quotient : quotient, modulus : modulus};
};
var haxe__$Int64__$_$_$Int64 = function(high,low) {
	this.high = high;
	this.low = low;
};
haxe__$Int64__$_$_$Int64.__name__ = true;
var haxe_ValueException = function(value,previous,native) {
	haxe_Exception.call(this,String(value),previous,native);
	this.value = value;
};
haxe_ValueException.__name__ = true;
haxe_ValueException.__super__ = haxe_Exception;
haxe_ValueException.prototype = $extend(haxe_Exception.prototype,{
});
var haxe_iterators_ArrayIterator = function(array) {
	this.current = 0;
	this.array = array;
};
haxe_iterators_ArrayIterator.__name__ = true;
haxe_iterators_ArrayIterator.prototype = {
	hasNext: function() {
		return this.current < this.array.length;
	}
	,next: function() {
		return this.array[this.current++];
	}
};
var js_Boot = function() { };
js_Boot.__name__ = true;
js_Boot.__string_rec = function(o,s) {
	if(o == null) {
		return "null";
	}
	if(s.length >= 5) {
		return "<...>";
	}
	var t = typeof(o);
	if(t == "function" && (o.__name__ || o.__ename__)) {
		t = "object";
	}
	switch(t) {
	case "function":
		return "<function>";
	case "object":
		if(((o) instanceof Array)) {
			var str = "[";
			s += "\t";
			var _g = 0;
			var _g1 = o.length;
			while(_g < _g1) {
				var i = _g++;
				str += (i > 0 ? "," : "") + js_Boot.__string_rec(o[i],s);
			}
			str += "]";
			return str;
		}
		var tostr;
		try {
			tostr = o.toString;
		} catch( _g ) {
			return "???";
		}
		if(tostr != null && tostr != Object.toString && typeof(tostr) == "function") {
			var s2 = o.toString();
			if(s2 != "[object Object]") {
				return s2;
			}
		}
		var str = "{\n";
		s += "\t";
		var hasp = o.hasOwnProperty != null;
		var k = null;
		for( k in o ) {
		if(hasp && !o.hasOwnProperty(k)) {
			continue;
		}
		if(k == "prototype" || k == "__class__" || k == "__super__" || k == "__interfaces__" || k == "__properties__") {
			continue;
		}
		if(str.length != 2) {
			str += ", \n";
		}
		str += s + k + " : " + js_Boot.__string_rec(o[k],s);
		}
		s = s.substring(1);
		str += "\n" + s + "}";
		return str;
	case "string":
		return o;
	default:
		return String(o);
	}
};
if(typeof(performance) != "undefined" ? typeof(performance.now) == "function" : false) {
	HxOverrides.now = performance.now.bind(performance);
}
String.__name__ = true;
Array.__name__ = true;
js_Boot.__toStr = ({ }).toString;
T11_$parallel_$sum.THREADS = 4;
T11_$parallel_$sum.SPAN = 25000000;
T11_$parallel_$sum.main();
})({});
