
#ifndef _C1_sy4_
#define _C1_sy4_

#ifdef __cplusplus
extern "C" {
#endif

RTOSHF (EIF_REFERENCE,59)
static EIF_REFERENCE F4_59_body(EIF_REFERENCE);
extern EIF_REFERENCE F4_59(EIF_REFERENCE);
RTOSHF (EIF_REFERENCE,60)
static EIF_REFERENCE F4_60_body(EIF_REFERENCE);
extern EIF_REFERENCE F4_60(EIF_REFERENCE);
RTOSHF (EIF_REFERENCE,62)
static EIF_REFERENCE F4_62_body(EIF_REFERENCE);
extern EIF_REFERENCE F4_62(EIF_REFERENCE);
RTOSHF (EIF_REFERENCE,64)
static EIF_REFERENCE F4_64_body(EIF_REFERENCE);
extern EIF_REFERENCE F4_64(EIF_REFERENCE);
extern void EIF_Minit4(void);
extern void F3_43(EIF_REFERENCE, EIF_REFERENCE);
extern EIF_REFERENCE F2_36(EIF_REFERENCE);
extern EIF_REFERENCE F35_581(EIF_REFERENCE);
extern EIF_REFERENCE F2_38(EIF_REFERENCE);
RTOSHF(EIF_REFERENCE,36)
RTOSHF(EIF_REFERENCE,38)

#ifdef __cplusplus
}
#endif

#endif
