// Generated by Haxe 4.3.7

#pragma warning disable 109, 114, 219, 429, 168, 162
namespace cs.io {
	public class NativeInput : global::haxe.io.Input {
		
		public NativeInput(global::haxe.lang.EmptyObject empty) : base(((global::haxe.lang.EmptyObject) (global::haxe.lang.EmptyObject.EMPTY) )) {
		}
		
		
		public NativeInput(global::System.IO.Stream stream) {
			#line 37 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\cs\\io\\NativeInput.hx"
			global::cs.io.NativeInput.__hx_ctor_cs_io_NativeInput(this, stream);
		}
		#line default
		
		protected static void __hx_ctor_cs_io_NativeInput(global::cs.io.NativeInput __hx_this, global::System.IO.Stream stream) {
			#line 38 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\cs\\io\\NativeInput.hx"
			__hx_this.stream = stream;
			__hx_this._eof = false;
			#line 40 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\cs\\io\\NativeInput.hx"
			if ( ! (stream.CanRead) ) {
				#line 41 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\cs\\io\\NativeInput.hx"
				throw ((global::System.Exception) (global::haxe.Exception.thrown("Write-only stream")) );
			}
			
		}
		#line default
		
		public global::System.IO.Stream stream;
		
		public bool _eof;
		
		public virtual int readBytes(global::haxe.io.Bytes s, int pos, int len) {
			#line 54 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\cs\\io\\NativeInput.hx"
			if (( ( ( pos < 0 ) || ( len < 0 ) ) || ( ( pos + len ) > s.length ) )) {
				#line 55 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\cs\\io\\NativeInput.hx"
				throw ((global::System.Exception) (global::haxe.Exception.thrown(global::haxe.io.Error.OutsideBounds)) );
			}
			
			#line 56 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\cs\\io\\NativeInput.hx"
			int ret = 0;
			byte[] data = s.b;
			#line 59 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\cs\\io\\NativeInput.hx"
			try {
				#line 59 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\cs\\io\\NativeInput.hx"
				ret = this.stream.Read(((byte[]) (data) ), ((int) (pos) ), ((int) (len) ));
			}
			catch (global::System.Exception _g){
			}
			
			
			#line 61 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\cs\\io\\NativeInput.hx"
			if (( ret == 0 )) {
				#line 62 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\cs\\io\\NativeInput.hx"
				this._eof = true;
				throw ((global::System.Exception) (global::haxe.Exception.thrown(new global::haxe.io.Eof())) );
			}
			
			#line 65 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\cs\\io\\NativeInput.hx"
			return ret;
		}
		#line default
		
		public virtual void close() {
			#line 69 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\cs\\io\\NativeInput.hx"
			this.stream.Close();
		}
		#line default
		
		public override object __hx_setField(string field, int hash, object @value, bool handleProperties) {
			unchecked {
				#line 31 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\cs\\io\\NativeInput.hx"
				switch (hash) {
					case 1058556349:
					{
						#line 31 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\cs\\io\\NativeInput.hx"
						this._eof = global::haxe.lang.Runtime.toBool(@value);
						#line 31 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\cs\\io\\NativeInput.hx"
						return @value;
					}
					
					
					case 288167040:
					{
						#line 31 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\cs\\io\\NativeInput.hx"
						this.stream = ((global::System.IO.Stream) (@value) );
						#line 31 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\cs\\io\\NativeInput.hx"
						return @value;
					}
					
					
					default:
					{
						#line 31 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\cs\\io\\NativeInput.hx"
						return base.__hx_setField(field, hash, @value, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override object __hx_getField(string field, int hash, bool throwErrors, bool isCheck, bool handleProperties) {
			unchecked {
				#line 31 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\cs\\io\\NativeInput.hx"
				switch (hash) {
					case 1214453688:
					{
						#line 31 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\cs\\io\\NativeInput.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "close", 1214453688)) );
					}
					
					
					case 243225909:
					{
						#line 31 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\cs\\io\\NativeInput.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "readBytes", 243225909)) );
					}
					
					
					case 1058556349:
					{
						#line 31 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\cs\\io\\NativeInput.hx"
						return this._eof;
					}
					
					
					case 288167040:
					{
						#line 31 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\cs\\io\\NativeInput.hx"
						return this.stream;
					}
					
					
					default:
					{
						#line 31 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\cs\\io\\NativeInput.hx"
						return base.__hx_getField(field, hash, throwErrors, isCheck, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override object __hx_invokeField(string field, int hash, object[] dynargs) {
			unchecked {
				#line 31 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\cs\\io\\NativeInput.hx"
				switch (hash) {
					case 1214453688:
					{
						#line 31 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\cs\\io\\NativeInput.hx"
						this.close();
						#line 31 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\cs\\io\\NativeInput.hx"
						break;
					}
					
					
					case 243225909:
					{
						#line 31 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\cs\\io\\NativeInput.hx"
						return this.readBytes(((global::haxe.io.Bytes) (dynargs[0]) ), ((int) (global::haxe.lang.Runtime.toInt(dynargs[1])) ), ((int) (global::haxe.lang.Runtime.toInt(dynargs[2])) ));
					}
					
					
					default:
					{
						#line 31 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\cs\\io\\NativeInput.hx"
						return base.__hx_invokeField(field, hash, dynargs);
					}
					
				}
				
				#line 31 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\cs\\io\\NativeInput.hx"
				return null;
			}
			#line default
		}
		
		
		public override void __hx_getFields(global::Array<string> baseArr) {
			#line 31 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\cs\\io\\NativeInput.hx"
			baseArr.push("_eof");
			#line 31 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\cs\\io\\NativeInput.hx"
			baseArr.push("stream");
			#line 31 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\cs\\io\\NativeInput.hx"
			base.__hx_getFields(baseArr);
		}
		#line default
		
	}
}


