// Generated by Haxe 4.3.7

#pragma warning disable 109, 114, 219, 429, 168, 162
namespace haxe {
	public class MainEvent : global::haxe.lang.HxObject {
		
		public MainEvent(global::haxe.lang.EmptyObject empty) {
		}
		
		
		public MainEvent(global::haxe.lang.Function f, int p) {
			#line 22 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\MainLoop.hx"
			global::haxe.MainEvent.__hx_ctor_haxe_MainEvent(this, f, p);
		}
		#line default
		
		protected static void __hx_ctor_haxe_MainEvent(global::haxe.MainEvent __hx_this, global::haxe.lang.Function f, int p) {
			#line 17 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\MainLoop.hx"
			__hx_this.isBlocking = true;
			#line 22 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\MainLoop.hx"
			{
				#line 23 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\MainLoop.hx"
				__hx_this.f = f;
				__hx_this.priority = p;
				#line 25 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\MainLoop.hx"
				__hx_this.nextRun = global::Math.NEGATIVE_INFINITY;
			}
			
		}
		#line default
		
		public global::haxe.lang.Function f;
		
		public global::haxe.MainEvent prev;
		
		public global::haxe.MainEvent next;
		
		public bool isBlocking;
		
		public double nextRun;
		
		public int priority;
		
		public override double __hx_setField_f(string field, int hash, double @value, bool handleProperties) {
			unchecked {
				#line 9 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\MainLoop.hx"
				switch (hash) {
					case 993950564:
					{
						#line 9 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\MainLoop.hx"
						this.priority = ((int) (@value) );
						#line 9 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\MainLoop.hx"
						return @value;
					}
					
					
					case 625308696:
					{
						#line 9 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\MainLoop.hx"
						this.nextRun = ((double) (@value) );
						#line 9 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\MainLoop.hx"
						return @value;
					}
					
					
					default:
					{
						#line 9 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\MainLoop.hx"
						return base.__hx_setField_f(field, hash, @value, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override object __hx_setField(string field, int hash, object @value, bool handleProperties) {
			unchecked {
				#line 9 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\MainLoop.hx"
				switch (hash) {
					case 993950564:
					{
						#line 9 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\MainLoop.hx"
						this.priority = ((int) (global::haxe.lang.Runtime.toInt(@value)) );
						#line 9 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\MainLoop.hx"
						return @value;
					}
					
					
					case 625308696:
					{
						#line 9 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\MainLoop.hx"
						this.nextRun = ((double) (global::haxe.lang.Runtime.toDouble(@value)) );
						#line 9 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\MainLoop.hx"
						return @value;
					}
					
					
					case 341784511:
					{
						#line 9 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\MainLoop.hx"
						this.isBlocking = global::haxe.lang.Runtime.toBool(@value);
						#line 9 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\MainLoop.hx"
						return @value;
					}
					
					
					case 1224901875:
					{
						#line 9 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\MainLoop.hx"
						this.next = ((global::haxe.MainEvent) (@value) );
						#line 9 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\MainLoop.hx"
						return @value;
					}
					
					
					case 1247723251:
					{
						#line 9 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\MainLoop.hx"
						this.prev = ((global::haxe.MainEvent) (@value) );
						#line 9 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\MainLoop.hx"
						return @value;
					}
					
					
					case 102:
					{
						#line 9 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\MainLoop.hx"
						this.f = ((global::haxe.lang.Function) (@value) );
						#line 9 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\MainLoop.hx"
						return @value;
					}
					
					
					default:
					{
						#line 9 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\MainLoop.hx"
						return base.__hx_setField(field, hash, @value, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override object __hx_getField(string field, int hash, bool throwErrors, bool isCheck, bool handleProperties) {
			unchecked {
				#line 9 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\MainLoop.hx"
				switch (hash) {
					case 993950564:
					{
						#line 9 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\MainLoop.hx"
						return this.priority;
					}
					
					
					case 625308696:
					{
						#line 9 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\MainLoop.hx"
						return this.nextRun;
					}
					
					
					case 341784511:
					{
						#line 9 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\MainLoop.hx"
						return this.isBlocking;
					}
					
					
					case 1224901875:
					{
						#line 9 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\MainLoop.hx"
						return this.next;
					}
					
					
					case 1247723251:
					{
						#line 9 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\MainLoop.hx"
						return this.prev;
					}
					
					
					case 102:
					{
						#line 9 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\MainLoop.hx"
						return this.f;
					}
					
					
					default:
					{
						#line 9 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\MainLoop.hx"
						return base.__hx_getField(field, hash, throwErrors, isCheck, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override double __hx_getField_f(string field, int hash, bool throwErrors, bool handleProperties) {
			unchecked {
				#line 9 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\MainLoop.hx"
				switch (hash) {
					case 993950564:
					{
						#line 9 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\MainLoop.hx"
						return ((double) (this.priority) );
					}
					
					
					case 625308696:
					{
						#line 9 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\MainLoop.hx"
						return this.nextRun;
					}
					
					
					default:
					{
						#line 9 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\MainLoop.hx"
						return base.__hx_getField_f(field, hash, throwErrors, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override void __hx_getFields(global::Array<string> baseArr) {
			#line 9 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\MainLoop.hx"
			baseArr.push("priority");
			#line 9 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\MainLoop.hx"
			baseArr.push("nextRun");
			#line 9 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\MainLoop.hx"
			baseArr.push("isBlocking");
			#line 9 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\MainLoop.hx"
			baseArr.push("next");
			#line 9 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\MainLoop.hx"
			baseArr.push("prev");
			#line 9 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\MainLoop.hx"
			baseArr.push("f");
			#line 9 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\MainLoop.hx"
			base.__hx_getFields(baseArr);
		}
		#line default
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace haxe {
	public class MainLoop : global::haxe.lang.HxObject {
		
		public MainLoop(global::haxe.lang.EmptyObject empty) {
		}
		
		
		public MainLoop() {
			#line 62 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\MainLoop.hx"
			global::haxe.MainLoop.__hx_ctor_haxe_MainLoop(this);
		}
		#line default
		
		protected static void __hx_ctor_haxe_MainLoop(global::haxe.MainLoop __hx_this) {
		}
		
		
		public static global::haxe.MainEvent pending;
		
		public static bool hasEvents() {
			#line 72 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\MainLoop.hx"
			global::haxe.MainEvent p = global::haxe.MainLoop.pending;
			while (( p != null )) {
				#line 74 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\MainLoop.hx"
				if (p.isBlocking) {
					#line 75 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\MainLoop.hx"
					return true;
				}
				
				#line 76 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\MainLoop.hx"
				p = p.next;
			}
			
			#line 78 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\MainLoop.hx"
			return false;
		}
		#line default
		
		public static void sortEvents() {
			unchecked {
				#line 108 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\MainLoop.hx"
				global::haxe.MainEvent list = global::haxe.MainLoop.pending;
				#line 110 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\MainLoop.hx"
				if (( list == null )) {
					#line 111 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\MainLoop.hx"
					return;
				}
				
				#line 113 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\MainLoop.hx"
				int insize = 1;
				#line 113 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\MainLoop.hx"
				int nmerges = default(int);
				#line 113 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\MainLoop.hx"
				int psize = 0;
				#line 113 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\MainLoop.hx"
				int qsize = 0;
				global::haxe.MainEvent p = null;
				global::haxe.MainEvent q = null;
				global::haxe.MainEvent e = null;
				global::haxe.MainEvent tail = null;
				#line 116 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\MainLoop.hx"
				while (true) {
					#line 117 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\MainLoop.hx"
					p = list;
					list = null;
					#line 119 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\MainLoop.hx"
					tail = null;
					nmerges = 0;
					#line 121 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\MainLoop.hx"
					while (( p != null )) {
						#line 122 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\MainLoop.hx"
						 ++ nmerges;
						q = p;
						#line 124 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\MainLoop.hx"
						psize = 0;
						{
							#line 125 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\MainLoop.hx"
							int _g = 0;
							#line 125 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\MainLoop.hx"
							int _g1 = insize;
							#line 125 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\MainLoop.hx"
							while (( _g < _g1 )) {
								#line 125 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\MainLoop.hx"
								int i = _g++;
								 ++ psize;
								#line 127 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\MainLoop.hx"
								q = q.next;
								if (( q == null )) {
									#line 129 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\MainLoop.hx"
									break;
								}
								
							}
							
						}
						
						#line 131 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\MainLoop.hx"
						qsize = insize;
						while (( ( psize > 0 ) || ( ( qsize > 0 ) && ( q != null ) ) )) {
							#line 133 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\MainLoop.hx"
							if (( psize == 0 )) {
								#line 134 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\MainLoop.hx"
								e = q;
								q = q.next;
								#line 136 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\MainLoop.hx"
								 -- qsize;
							}
							else if (( ( ( qsize == 0 ) || ( q == null ) ) || (( ( p.priority > q.priority ) || ( ( p.priority == q.priority ) && ( p.nextRun <= q.nextRun ) ) )) )) {
								#line 140 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\MainLoop.hx"
								e = p;
								p = p.next;
								#line 142 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\MainLoop.hx"
								 -- psize;
							}
							else {
								#line 144 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\MainLoop.hx"
								e = q;
								q = q.next;
								#line 146 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\MainLoop.hx"
								 -- qsize;
							}
							
							#line 148 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\MainLoop.hx"
							if (( tail != null )) {
								#line 149 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\MainLoop.hx"
								tail.next = e;
							}
							else {
								#line 151 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\MainLoop.hx"
								list = e;
							}
							
							#line 152 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\MainLoop.hx"
							e.prev = tail;
							tail = e;
						}
						
						#line 155 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\MainLoop.hx"
						p = q;
					}
					
					#line 157 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\MainLoop.hx"
					tail.next = null;
					if (( nmerges <= 1 )) {
						#line 159 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\MainLoop.hx"
						break;
					}
					
					#line 160 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\MainLoop.hx"
					insize *= 2;
				}
				
				#line 162 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\MainLoop.hx"
				list.prev = null;
				global::haxe.MainLoop.pending = list;
			}
			#line default
		}
		
		
		public static double tick() {
			#line 170 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\MainLoop.hx"
			global::haxe.MainLoop.sortEvents();
			global::haxe.MainEvent e = global::haxe.MainLoop.pending;
			#line 172 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\MainLoop.hx"
			double now = global::Sys.time();
			double wait = 1e9;
			#line 174 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\MainLoop.hx"
			while (( e != null )) {
				#line 175 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\MainLoop.hx"
				global::haxe.MainEvent next = e.next;
				double wt = ( e.nextRun - now );
				#line 177 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\MainLoop.hx"
				if (( wt <= 0 )) {
					#line 178 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\MainLoop.hx"
					wait = ((double) (0) );
					if (( e.f != null )) {
						#line 179 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\MainLoop.hx"
						e.f.__hx_invoke0_o();
					}
					
				}
				else if (( wait > wt )) {
					#line 181 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\MainLoop.hx"
					wait = wt;
				}
				
				#line 182 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\MainLoop.hx"
				e = next;
			}
			
			#line 184 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\haxe\\MainLoop.hx"
			return wait;
		}
		#line default
		
	}
}


