
#ifndef _C1_co19_
#define _C1_co19_

#ifdef __cplusplus
extern "C" {
#endif

RTOSHF (EIF_REFERENCE,544)
static EIF_REFERENCE F31_544_body(EIF_REFERENCE);
extern EIF_REFERENCE F31_544(EIF_REFERENCE);
RTOSHF (EIF_REFERENCE,545)
static EIF_REFERENCE F31_545_body(EIF_REFERENCE);
extern EIF_REFERENCE F31_545(EIF_REFERENCE);
RTOSHF (EIF_REFERENCE,546)
static EIF_REFERENCE F31_546_body(EIF_REFERENCE);
extern EIF_REFERENCE F31_546(EIF_REFERENCE);
RTOSHF (EIF_REFERENCE,547)
static EIF_REFERENCE F31_547_body(EIF_REFERENCE);
extern EIF_REFERENCE F31_547(EIF_REFERENCE);
extern void EIF_Minit19(void);
extern void F598_3037(EIF_REFERENCE, EIF_INTEGER_32);
extern EIF_REFERENCE F3_42(EIF_REFERENCE);
extern void F594_2971(EIF_REFERENCE, EIF_REFERENCE, EIF_REFERENCE);
extern EIF_REFERENCE F3_47(EIF_REFERENCE);
extern EIF_REFERENCE F783_5046(EIF_REFERENCE);
extern EIF_REFERENCE F3_44(EIF_REFERENCE);
extern EIF_REFERENCE F3_46(EIF_REFERENCE);
extern EIF_REFERENCE F3_49(EIF_REFERENCE);
extern EIF_REFERENCE F3_43(EIF_REFERENCE);
extern EIF_REFERENCE F3_45(EIF_REFERENCE);
extern EIF_REFERENCE F3_48(EIF_REFERENCE);
RTOSHF(EIF_REFERENCE,42)
RTOSHF(EIF_REFERENCE,43)
RTOSHF(EIF_REFERENCE,44)
RTOSHF(EIF_REFERENCE,46)
RTOSHF(EIF_REFERENCE,45)
RTOSHF(EIF_REFERENCE,47)
RTOSHF(EIF_REFERENCE,48)
RTOSHF(EIF_REFERENCE,49)

#ifdef __cplusplus
}
#endif

#endif
