
#ifndef _C1_co3_
#define _C1_co3_

#ifdef __cplusplus
extern "C" {
#endif
RTOSHF (EIF_REFERENCE, 42)


extern EIF_REFERENCE F3_42(EIF_REFERENCE);RTOSHF (EIF_REFERENCE, 43)


extern EIF_REFERENCE F3_43(EIF_REFERENCE);RTOSHF (EIF_REFERENCE, 44)


extern EIF_REFERENCE F3_44(EIF_REFERENCE);RTOSHF (EIF_REFERENCE, 45)


extern EIF_REFERENCE F3_45(EIF_REFERENCE);RTOSHF (EIF_REFERENCE, 46)


extern EIF_REFERENCE F3_46(EIF_REFERENCE);RTOSHF (EIF_REFERENCE, 47)


extern EIF_REFERENCE F3_47(EIF_REFERENCE);RTOSHF (EIF_REFERENCE, 48)


extern EIF_REFERENCE F3_48(EIF_REFERENCE);RTOSHF (EIF_REFERENCE, 49)


extern EIF_REFERENCE F3_49(EIF_REFERENCE);
extern void EIF_Minit3(void);

#ifdef __cplusplus
}
#endif

#endif
