<?php
/**
 * Generated by Haxe 4.3.7
 */

use \php\Boot;

class AddOne {
	/**
	 * @param int $n
	 * 
	 * @return int
	 */
	public static function add_one ($n) {
		#AddOne.hx:9: characters 9-21
		return $n + 1;
	}
}

Boot::registerClass(AddOne::class, 'AddOne');
