<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace></RootNamespace>
    <OptionStrict>Off</OptionStrict>
    <Optimize>true</Optimize>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>

</Project>
