<?php
/**
 * Generated by Haxe 4.3.7
 */

use \haxe\_Int64\Int64_Impl_;
use \haxe\_Int64\___Int64;
use \php\Boot;
use \haxe\Exception as HaxeException;
use \haxe\_Int32\Int32_Impl_;

class Big {
	/**
	 * @var int
	 */
	const BASE = 1000000000;

	/**
	 * @var ___Int64
	 */
	static public $BASE64;

	/**
	 * @var int[]|\Array_hx
	 */
	public $limb;
	/**
	 * @var int
	 */
	public $n;
	/**
	 * @var bool
	 */
	public $neg;

	/**
	 * @param Big $a
	 * @param Big $b
	 * @param Big $work
	 * 
	 * @return int
	 */
	public static function quot ($a, $b, $work) {
		#T10_pi.hx:184: characters 9-19
		$q = 0;
		#T10_pi.hx:185: lines 185-187
		if ($a->neg || $b->neg || ($b->n === 0)) {
			#T10_pi.hx:186: characters 13-21
			return 0;
		}
		#T10_pi.hx:188: characters 9-25
		$work->copyFrom($b);
		#T10_pi.hx:189: lines 189-192
		while ($a->cmp($work) >= 0) {
			#T10_pi.hx:190: characters 13-16
			++$q;
			#T10_pi.hx:191: characters 13-33
			$work->addMag($work, $b);
		}
		#T10_pi.hx:193: characters 9-17
		return $q;
	}

	/**
	 * @return void
	 */
	public function __construct () {
		#T10_pi.hx:22: characters 9-32
		$this->limb = new \Array_hx();
		#T10_pi.hx:23: characters 9-14
		$this->n = 0;
		#T10_pi.hx:24: characters 9-20
		$this->neg = false;
	}

	/**
	 * @param Big $r
	 * @param Big $b
	 * 
	 * @return void
	 */
	public function add ($r, $b) {
		#T10_pi.hx:126: characters 9-22
		$an = $this->neg;
		#T10_pi.hx:127: characters 9-24
		$bn = $b->neg;
		#T10_pi.hx:128: lines 128-137
		if ($an === $bn) {
			#T10_pi.hx:129: characters 13-25
			$this->addMag($r, $b);
			#T10_pi.hx:130: characters 13-23
			$r->neg = $an;
		} else if ($this->cmpMag($b) >= 0) {
			#T10_pi.hx:132: characters 13-25
			$this->subMag($r, $b);
			#T10_pi.hx:133: characters 13-23
			$r->neg = $an;
		} else {
			#T10_pi.hx:135: characters 13-30
			$b->subMag($r, $this);
			#T10_pi.hx:136: characters 13-23
			$r->neg = $bn;
		}
		#T10_pi.hx:138: characters 9-17
		$r->trim();
	}

	/**
	 * @param Big $r
	 * @param Big $b
	 * 
	 * @return void
	 */
	public function addMag ($r, $b) {
		#T10_pi.hx:83: characters 9-39
		$count = ($this->n > $b->n ? $this->n : $b->n);
		#T10_pi.hx:84: characters 9-29
		$r->reserve($count + 1);
		#T10_pi.hx:85: characters 9-23
		$carry = 0;
		#T10_pi.hx:86: characters 19-23
		$_g = 0;
		#T10_pi.hx:86: characters 23-28
		$_g1 = $count;
		#T10_pi.hx:86: lines 86-101
		while ($_g < $_g1) {
			#T10_pi.hx:86: characters 19-28
			$i = $_g++;
			#T10_pi.hx:87: characters 13-27
			$s = $carry;
			#T10_pi.hx:88: lines 88-90
			if ($i < $this->n) {
				#T10_pi.hx:89: characters 17-29
				$s += ($this->limb->arr[$i] ?? null);
			}
			#T10_pi.hx:91: lines 91-93
			if ($i < $b->n) {
				#T10_pi.hx:92: characters 17-31
				$s += ($b->limb->arr[$i] ?? null);
			}
			#T10_pi.hx:94: lines 94-99
			if ($s >= 1000000000) {
				#T10_pi.hx:95: characters 17-26
				$s -= 1000000000;
				#T10_pi.hx:96: characters 17-26
				$carry = 1;
			} else {
				#T10_pi.hx:98: characters 17-26
				$carry = 0;
			}
			#T10_pi.hx:100: characters 13-26
			$r->limb->offsetSet($i, $s);
		}
		#T10_pi.hx:102: characters 9-30
		$r->limb->offsetSet($count, $carry);
		#T10_pi.hx:103: characters 9-43
		$r->n = $count + (($carry !== 0 ? 1 : 0));
		#T10_pi.hx:104: characters 9-22
		$r->neg = false;
	}

	/**
	 * @param Big $b
	 * 
	 * @return int
	 */
	public function cmp ($b) {
		#T10_pi.hx:75: lines 75-77
		if ($this->neg !== $b->neg) {
			#T10_pi.hx:76: characters 20-32
			if ($this->neg) {
				#T10_pi.hx:76: characters 26-28
				return -1;
			} else {
				#T10_pi.hx:76: characters 31-32
				return 1;
			}
		}
		#T10_pi.hx:78: characters 9-27
		$c = $this->cmpMag($b);
		#T10_pi.hx:79: characters 16-28
		if ($this->neg) {
			#T10_pi.hx:79: characters 22-24
			return -$c;
		} else {
			#T10_pi.hx:79: characters 27-28
			return $c;
		}
	}

	/**
	 * @param Big $b
	 * 
	 * @return int
	 */
	public function cmpMag ($b) {
		#T10_pi.hx:62: lines 62-64
		if ($this->n !== $b->n) {
			#T10_pi.hx:63: characters 20-36
			if ($this->n < $b->n) {
				#T10_pi.hx:63: characters 30-32
				return -1;
			} else {
				#T10_pi.hx:63: characters 35-36
				return 1;
			}
		}
		#T10_pi.hx:65: characters 9-19
		$i = $this->n;
		#T10_pi.hx:66: lines 66-70
		while ($i-- > 0) {
			#T10_pi.hx:67: lines 67-69
			if (($this->limb->arr[$i] ?? null) !== ($b->limb->arr[$i] ?? null)) {
				#T10_pi.hx:68: characters 24-52
				if (($this->limb->arr[$i] ?? null) < ($b->limb->arr[$i] ?? null)) {
					#T10_pi.hx:68: characters 46-48
					return -1;
				} else {
					#T10_pi.hx:68: characters 51-52
					return 1;
				}
			}
		}
		#T10_pi.hx:71: characters 9-17
		return 0;
	}

	/**
	 * @param Big $src
	 * 
	 * @return void
	 */
	public function copyFrom ($src) {
		#T10_pi.hx:53: characters 9-23
		$this->reserve($src->n);
		#T10_pi.hx:54: characters 19-23
		$_g = 0;
		#T10_pi.hx:54: characters 23-28
		$_g1 = $src->n;
		#T10_pi.hx:54: lines 54-56
		while ($_g < $_g1) {
			#T10_pi.hx:54: characters 19-28
			$i = $_g++;
			#T10_pi.hx:55: characters 13-34
			$this->limb->offsetSet($i, ($src->limb->arr[$i] ?? null));
		}
		#T10_pi.hx:57: characters 9-18
		$this->n = $src->n;
		#T10_pi.hx:58: characters 9-22
		$this->neg = $src->neg;
	}

	/**
	 * @param Big $r
	 * @param int $m
	 * 
	 * @return void
	 */
	public function mulSmall ($r, $m) {
		#T10_pi.hx:158: lines 158-162
		if (($m === 0) || ($this->n === 0)) {
			#T10_pi.hx:159: characters 13-16
			$r->n = 0;
			#T10_pi.hx:160: characters 13-18
			$r->neg = false;
			#T10_pi.hx:161: characters 13-19
			return;
		}
		#T10_pi.hx:163: characters 9-25
		$r->reserve($this->n + 2);
		#T10_pi.hx:164: characters 9-41
		$carry = new ___Int64(0, 0);
		#T10_pi.hx:165: characters 19-23
		$_g = 0;
		#T10_pi.hx:165: characters 23-24
		$_g1 = $this->n;
		#T10_pi.hx:165: lines 165-169
		while ($_g < $_g1) {
			#T10_pi.hx:165: characters 19-24
			$i = $_g++;
			#T10_pi.hx:166: characters 21-46
			$x = ($this->limb->arr[$i] ?? null);
			$a_high = $x >> 31;
			$a_low = $x;
			#T10_pi.hx:166: characters 21-50
			$b_high = $m >> 31;
			$b_low = $m;
			$mask = 65535;
			$al = $a_low & $mask;
			$ah = Boot::shiftRightUnsigned($a_low, 16);
			$bl = $b_low & $mask;
			$bh = Boot::shiftRightUnsigned($b_low, 16);
			$p00 = Int32_Impl_::mul($al, $bl);
			$p10 = Int32_Impl_::mul($ah, $bl);
			$p01 = Int32_Impl_::mul($al, $bh);
			$p11 = Int32_Impl_::mul($ah, $bh);
			$low = $p00;
			$high = ((((($p11 + (Boot::shiftRightUnsigned($p01, 16))) << Int32_Impl_::$extraBits) >> Int32_Impl_::$extraBits) + (Boot::shiftRightUnsigned($p10, 16))) << Int32_Impl_::$extraBits) >> Int32_Impl_::$extraBits;
			#D:\Users\pedro.cardoso\stupidspeed\tools\haxe\std/haxe/Int64.hx:302: characters 3-6
			$p01 = ($p01 << 16 << Int32_Impl_::$extraBits) >> Int32_Impl_::$extraBits;
			#D:\Users\pedro.cardoso\stupidspeed\tools\haxe\std/haxe/Int64.hx:303: characters 3-6
			$low = (($low + $p01) << Int32_Impl_::$extraBits) >> Int32_Impl_::$extraBits;
			#T10_pi.hx:166: characters 21-50
			if (Int32_Impl_::ucompare($low, $p01) < 0) {
				$ret = $high++;
				#D:\Users\pedro.cardoso\stupidspeed\tools\haxe\std/haxe/Int64.hx:305: characters 4-8
				$high = ($high << Int32_Impl_::$extraBits) >> Int32_Impl_::$extraBits;
			}
			#D:\Users\pedro.cardoso\stupidspeed\tools\haxe\std/haxe/Int64.hx:306: characters 3-6
			$p10 = ($p10 << 16 << Int32_Impl_::$extraBits) >> Int32_Impl_::$extraBits;
			#D:\Users\pedro.cardoso\stupidspeed\tools\haxe\std/haxe/Int64.hx:307: characters 3-6
			$low = (($low + $p10) << Int32_Impl_::$extraBits) >> Int32_Impl_::$extraBits;
			#T10_pi.hx:166: characters 21-50
			if (Int32_Impl_::ucompare($low, $p10) < 0) {
				$ret1 = $high++;
				#D:\Users\pedro.cardoso\stupidspeed\tools\haxe\std/haxe/Int64.hx:309: characters 4-8
				$high = ($high << Int32_Impl_::$extraBits) >> Int32_Impl_::$extraBits;
			}
			#T10_pi.hx:166: characters 21-50
			$high = (($high + (((Int32_Impl_::mul($a_low, $b_high) + Int32_Impl_::mul($a_high, $b_low)) << Int32_Impl_::$extraBits) >> Int32_Impl_::$extraBits)) << Int32_Impl_::$extraBits) >> Int32_Impl_::$extraBits;
			$a_high1 = $high;
			$a_low1 = $low;
			#T10_pi.hx:166: characters 21-58
			$high1 = (($a_high1 + $carry->high) << Int32_Impl_::$extraBits) >> Int32_Impl_::$extraBits;
			$low1 = (($a_low1 + $carry->low) << Int32_Impl_::$extraBits) >> Int32_Impl_::$extraBits;
			if (Int32_Impl_::ucompare($low1, $a_low1) < 0) {
				$ret2 = $high1++;
				#D:\Users\pedro.cardoso\stupidspeed\tools\haxe\std/haxe/Int64.hx:264: characters 4-8
				$high1 = ($high1 << Int32_Impl_::$extraBits) >> Int32_Impl_::$extraBits;
			}
			#T10_pi.hx:166: characters 13-59
			$p = new ___Int64($high1, $low1);
			#T10_pi.hx:167: characters 13-19
			$r1 = $r->limb;
			#T10_pi.hx:167: characters 25-53
			$x1 = Int64_Impl_::divMod($p, Big::$BASE64)->modulus;
			if ($x1->high !== ((($x1->low >> 31) << Int32_Impl_::$extraBits) >> Int32_Impl_::$extraBits)) {
				throw HaxeException::thrown("Overflow");
			}
			#T10_pi.hx:167: characters 13-22
			$r1->offsetSet($i, $x1->low);
			#T10_pi.hx:168: characters 21-31
			$carry = Int64_Impl_::divMod($p, Big::$BASE64)->quotient;
		}
		#T10_pi.hx:170: characters 9-23
		$count = $this->n;
		#T10_pi.hx:171: lines 171-175
		while (true) {
			#T10_pi.hx:171: characters 16-25
			$b_high = 0;
			$b_low = 0;
			$v = (($carry->high - $b_high) << Int32_Impl_::$extraBits) >> Int32_Impl_::$extraBits;
			if ($v === 0) {
				$v = Int32_Impl_::ucompare($carry->low, $b_low);
			}
			#T10_pi.hx:171: lines 171-175
			if (!((($carry->high < 0 ? ($b_high < 0 ? $v : -1) : ($b_high >= 0 ? $v : 1))) > 0)) {
				break;
			}
			#T10_pi.hx:172: characters 13-33
			$r->reserve($count + 1);
			#T10_pi.hx:173: characters 13-19
			$r1 = $r->limb;
			#T10_pi.hx:173: characters 20-27
			$tmp = $count++;
			#T10_pi.hx:173: characters 31-63
			$x = Int64_Impl_::divMod($carry, Big::$BASE64)->modulus;
			if ($x->high !== ((($x->low >> 31) << Int32_Impl_::$extraBits) >> Int32_Impl_::$extraBits)) {
				throw HaxeException::thrown("Overflow");
			}
			#T10_pi.hx:173: characters 13-28
			$r1->offsetSet($tmp, $x->low);
			#T10_pi.hx:174: characters 21-35
			$carry = Int64_Impl_::divMod($carry, Big::$BASE64)->quotient;
		}
		#T10_pi.hx:176: characters 9-12
		$r->n = $count;
		#T10_pi.hx:177: characters 9-14
		$r->neg = $this->neg;
		#T10_pi.hx:178: characters 9-17
		$r->trim();
	}

	/**
	 * @param int $need
	 * 
	 * @return void
	 */
	public function reserve ($need) {
		#T10_pi.hx:28: lines 28-30
		while ($this->limb->length < $need) {
			#T10_pi.hx:29: characters 13-25
			$_this = $this->limb;
			$_this->arr[$_this->length++] = 0;
		}
	}

	/**
	 * @param ___Int64 $v
	 * 
	 * @return void
	 */
	public function set ($v) {
		#T10_pi.hx:43: characters 9-10
		$this->n = 0;
		#T10_pi.hx:44: characters 9-12
		$this->neg = false;
		#T10_pi.hx:45: lines 45-49
		while (true) {
			#T10_pi.hx:45: characters 16-21
			$b_high = 0;
			$b_low = 0;
			$v1 = (($v->high - $b_high) << Int32_Impl_::$extraBits) >> Int32_Impl_::$extraBits;
			if ($v1 === 0) {
				$v1 = Int32_Impl_::ucompare($v->low, $b_low);
			}
			#T10_pi.hx:45: lines 45-49
			if (!((($v->high < 0 ? ($b_high < 0 ? $v1 : -1) : ($b_high >= 0 ? $v1 : 1))) > 0)) {
				break;
			}
			#T10_pi.hx:46: characters 13-27
			$this->reserve($this->n + 1);
			#T10_pi.hx:47: characters 13-17
			$tmp = $this->limb;
			#T10_pi.hx:47: characters 18-21
			$tmp1 = $this->n++;
			#T10_pi.hx:47: characters 25-53
			$x = Int64_Impl_::divMod($v, Big::$BASE64)->modulus;
			if ($x->high !== ((($x->low >> 31) << Int32_Impl_::$extraBits) >> Int32_Impl_::$extraBits)) {
				throw HaxeException::thrown("Overflow");
			}
			#T10_pi.hx:47: characters 13-22
			$tmp->offsetSet($tmp1, $x->low);
			#T10_pi.hx:48: characters 17-27
			$v = Int64_Impl_::divMod($v, Big::$BASE64)->quotient;
		}
	}

	/**
	 * @param Big $r
	 * @param Big $b
	 * 
	 * @return void
	 */
	public function sub ($r, $b) {
		#T10_pi.hx:142: characters 9-22
		$an = $this->neg;
		#T10_pi.hx:143: characters 9-24
		$bn = $b->neg;
		#T10_pi.hx:144: lines 144-153
		if ($an !== $bn) {
			#T10_pi.hx:145: characters 13-25
			$this->addMag($r, $b);
			#T10_pi.hx:146: characters 13-23
			$r->neg = $an;
		} else if ($this->cmpMag($b) >= 0) {
			#T10_pi.hx:148: characters 13-25
			$this->subMag($r, $b);
			#T10_pi.hx:149: characters 13-23
			$r->neg = $an;
		} else {
			#T10_pi.hx:151: characters 13-30
			$b->subMag($r, $this);
			#T10_pi.hx:152: characters 13-24
			$r->neg = !$an;
		}
		#T10_pi.hx:154: characters 9-17
		$r->trim();
	}

	/**
	 * @param Big $r
	 * @param Big $b
	 * 
	 * @return void
	 */
	public function subMag ($r, $b) {
		#T10_pi.hx:108: characters 9-21
		$r->reserve($this->n);
		#T10_pi.hx:109: characters 9-24
		$borrow = 0;
		#T10_pi.hx:110: characters 19-23
		$_g = 0;
		#T10_pi.hx:110: characters 23-24
		$_g1 = $this->n;
		#T10_pi.hx:110: lines 110-119
		while ($_g < $_g1) {
			#T10_pi.hx:110: characters 19-24
			$i = $_g++;
			#T10_pi.hx:111: characters 13-57
			$bi = (($i < $b->n ? ($b->limb->arr[$i] ?? null) : 0)) + $borrow;
			#T10_pi.hx:112: lines 112-118
			if (($this->limb->arr[$i] ?? null) >= $bi) {
				#T10_pi.hx:113: characters 17-41
				$r->limb->offsetSet($i, ($this->limb->arr[$i] ?? null) - $bi);
				#T10_pi.hx:114: characters 17-27
				$borrow = 0;
			} else {
				#T10_pi.hx:116: characters 17-48
				$r->limb->offsetSet($i, ($this->limb->arr[$i] ?? null) + 1000000000 - $bi);
				#T10_pi.hx:117: characters 17-27
				$borrow = 1;
			}
		}
		#T10_pi.hx:120: characters 9-16
		$r->n = $this->n;
		#T10_pi.hx:121: characters 9-22
		$r->neg = false;
		#T10_pi.hx:122: characters 9-17
		$r->trim();
	}

	/**
	 * @return void
	 */
	public function trim () {
		#T10_pi.hx:34: lines 34-36
		while (($this->n > 0) && (($this->limb->arr[$this->n - 1] ?? null) === 0)) {
			#T10_pi.hx:35: characters 13-16
			$this->n--;
		}
		#T10_pi.hx:37: lines 37-39
		if ($this->n === 0) {
			#T10_pi.hx:38: characters 13-24
			$this->neg = false;
		}
	}

	/**
	 * @internal
	 * @access private
	 */
	static public function __hx__init ()
	{
		static $called = false;
		if ($called) return;
		$called = true;


		self::$BASE64 = new ___Int64(0, 1000000000);
	}
}

Boot::registerClass(Big::class, 'Big');
Big::__hx__init();
