<?php
/**
 * Generated by Haxe 4.3.7
 */

use \haxe\_Int64\___Int64;
use \php\Boot;

class T10_pi {
	/**
	 * @return void
	 */
	public static function main () {
		#T10_pi.hx:200: characters 9-37
		$t0 = microtime(true);
		#T10_pi.hx:201: characters 9-27
		$q = new \Big();
		#T10_pi.hx:202: characters 9-27
		$r = new \Big();
		#T10_pi.hx:203: characters 9-27
		$t = new \Big();
		#T10_pi.hx:204: characters 9-27
		$u = new \Big();
		#T10_pi.hx:205: characters 9-27
		$v = new \Big();
		#T10_pi.hx:206: characters 9-27
		$w = new \Big();
		#T10_pi.hx:208: characters 9-35
		$q->set(new ___Int64(0, 1));
		#T10_pi.hx:209: characters 9-35
		$r->set(new ___Int64(0, 0));
		#T10_pi.hx:210: characters 9-35
		$t->set(new ___Int64(0, 1));
		#T10_pi.hx:212: characters 9-19
		$k = 1;
		#T10_pi.hx:213: characters 9-19
		$l = 3;
		#T10_pi.hx:214: characters 9-19
		$n = 3;
		#T10_pi.hx:215: characters 9-21
		$sum = 0;
		#T10_pi.hx:217: characters 9-26
		$produced = 0;
		#T10_pi.hx:218: lines 218-258
		while ($produced < 1000) {
			#T10_pi.hx:219: characters 13-29
			$q->mulSmall($u, 4);
			#T10_pi.hx:220: characters 13-24
			$u->add($u, $r);
			#T10_pi.hx:221: characters 13-33
			$t->mulSmall($v, $n + 1);
			#T10_pi.hx:223: lines 223-257
			if ($u->cmp($v) < 0) {
				#T10_pi.hx:225: characters 17-25
				$sum += $n;
				#T10_pi.hx:226: characters 17-27
				++$produced;
				#T10_pi.hx:228: characters 17-33
				$q->mulSmall($u, 3);
				#T10_pi.hx:229: characters 17-28
				$u->add($u, $r);
				#T10_pi.hx:230: characters 17-34
				$u->mulSmall($u, 10);
				#T10_pi.hx:231: characters 17-55
				$next = \Big::quot($u, $t, $w) - 10 * $n;
				#T10_pi.hx:233: characters 17-33
				$t->mulSmall($v, $n);
				#T10_pi.hx:234: characters 17-28
				$r->sub($v, $v);
				#T10_pi.hx:235: characters 17-34
				$v->mulSmall($r, 10);
				#T10_pi.hx:236: characters 17-34
				$q->mulSmall($q, 10);
				#T10_pi.hx:238: characters 17-25
				$n = $next;
			} else {
				#T10_pi.hx:241: characters 17-41
				$q->mulSmall($u, 7 * $k + 2);
				#T10_pi.hx:242: characters 17-33
				$r->mulSmall($v, $l);
				#T10_pi.hx:243: characters 17-28
				$u->add($u, $v);
				#T10_pi.hx:244: characters 17-33
				$t->mulSmall($v, $l);
				#T10_pi.hx:245: characters 17-46
				$next1 = \Big::quot($u, $v, $w);
				#T10_pi.hx:247: characters 17-33
				$q->mulSmall($u, 2);
				#T10_pi.hx:248: characters 17-28
				$u->add($u, $r);
				#T10_pi.hx:249: characters 17-33
				$u->mulSmall($u, $l);
				#T10_pi.hx:250: characters 17-30
				$r->copyFrom($u);
				#T10_pi.hx:251: characters 17-33
				$q->mulSmall($q, $k);
				#T10_pi.hx:252: characters 17-33
				$t->mulSmall($t, $l);
				#T10_pi.hx:254: characters 17-20
				++$k;
				#T10_pi.hx:255: characters 17-23
				$l += 2;
				#T10_pi.hx:256: characters 17-25
				$n = $next1;
			}
		}
		#T10_pi.hx:260: characters 9-37
		$t1 = microtime(true);
		#T10_pi.hx:261: characters 9-58
		\Out::err("TIME_MS=" . (($t1 - $t0) * 1000.0) . "\x0A");
		#T10_pi.hx:262: characters 9-22
		\Out::line($sum);
	}
}

Boot::registerClass(T10_pi::class, 'T10_pi');
