// Generated by Haxe 4.3.7

#pragma warning disable 109, 114, 219, 429, 168, 162
namespace sys.thread {
	public class EventLoop : global::haxe.lang.HxObject {
		
		public EventLoop(global::haxe.lang.EmptyObject empty) {
		}
		
		
		public EventLoop() {
			#line 34 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
			global::sys.thread.EventLoop.__hx_ctor_sys_thread_EventLoop(this);
		}
		#line default
		
		protected static void __hx_ctor_sys_thread_EventLoop(global::sys.thread.EventLoop __hx_this) {
			#line 29 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
			__hx_this.promisedEventsCount = 0;
			#line 28 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
			__hx_this.waitLock = new global::sys.thread.Lock();
			#line 27 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
			__hx_this.oneTimeEventsIdx = 0;
			#line 26 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
			__hx_this.oneTimeEvents = new global::Array<object>();
			#line 25 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
			__hx_this.mutex = new global::sys.thread.Mutex();
			#line 34 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
			{
				#line 35 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
				__hx_this.isMainThread =  ! (global::sys.thread.EventLoop.CREATED) ;
				global::sys.thread.EventLoop.CREATED = true;
			}
			
		}
		#line default
		
		public static bool CREATED;
		
		public global::sys.thread.Mutex mutex;
		
		public global::Array<object> oneTimeEvents;
		
		public int oneTimeEventsIdx;
		
		public global::sys.thread.Lock waitLock;
		
		public int promisedEventsCount;
		
		public global::sys.thread._EventLoop.RegularEvent regularEvents;
		
		public bool isMainThread;
		
		public virtual void loop() {
			unchecked {
				#line 180 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
				global::Array<object> recycleRegular = new global::Array<object>(new object[]{});
				global::Array<object> recycleOneTimers = new global::Array<object>(new object[]{});
				#line 182 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
				while (true) {
					#line 183 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
					double now = global::Sys.time();
					#line 183 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
					global::Array<object> regularsToRun = recycleRegular;
					#line 183 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
					int eventsToRunIdx = 0;
					#line 183 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
					double nextEventAt = ((double) (-1) );
					#line 183 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
					this.mutex.acquire();
					#line 183 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
					while (this.waitLock.wait(new global::haxe.lang.Null<double>(0.0, true))) {
					}
					
					#line 183 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
					global::sys.thread._EventLoop.RegularEvent current = this.regularEvents;
					#line 183 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
					while (( current != null )) {
						#line 183 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
						if (( current.nextRunTime <= now )) {
							#line 183 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
							regularsToRun[eventsToRunIdx++] = current;
							#line 183 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
							current.nextRunTime += current.interval;
							#line 220 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
							nextEventAt = ((double) (-2) );
						}
						else if (( ( nextEventAt == -1 ) || ( current.nextRunTime < nextEventAt ) )) {
							#line 222 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
							nextEventAt = current.nextRunTime;
						}
						
						#line 224 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
						current = current.next;
					}
					
					#line 183 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
					this.mutex.release();
					#line 183 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
					int _g = 0;
					#line 183 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
					int _g1 = eventsToRunIdx;
					#line 183 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
					while (( _g < _g1 )) {
						#line 183 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
						int i = _g++;
						#line 183 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
						if ( ! (((global::sys.thread._EventLoop.RegularEvent) (regularsToRun[i]) ).cancelled) ) {
							#line 183 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
							((global::sys.thread._EventLoop.RegularEvent) (regularsToRun[i]) ).run.__hx_invoke0_o();
						}
						
						#line 183 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
						regularsToRun[i] = null;
					}
					
					#line 234 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
					eventsToRunIdx = 0;
					#line 183 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
					global::Array<object> oneTimersToRun = recycleOneTimers;
					#line 183 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
					this.mutex.acquire();
					#line 183 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
					int _g_current = 0;
					#line 183 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
					global::Array<object> _g_array = this.oneTimeEvents;
					#line 183 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
					while (( _g_current < _g_array.length )) {
						#line 183 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
						global::haxe.lang.Function _g_value = ((global::haxe.lang.Function) (_g_array[_g_current]) );
						#line 183 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
						int _g_key = _g_current++;
						#line 183 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
						int i1 = _g_key;
						#line 183 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
						global::haxe.lang.Function @event = _g_value;
						#line 183 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
						if (( @event == null )) {
							#line 183 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
							break;
						}
						else {
							#line 183 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
							oneTimersToRun[eventsToRunIdx++] = @event;
							#line 183 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
							this.oneTimeEvents[i1] = null;
						}
						
					}
					
					#line 183 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
					this.oneTimeEventsIdx = 0;
					#line 183 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
					bool hasPromisedEvents = ( this.promisedEventsCount > 0 );
					#line 183 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
					this.mutex.release();
					#line 183 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
					int _g2 = 0;
					#line 183 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
					int _g3 = eventsToRunIdx;
					#line 183 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
					while (( _g2 < _g3 )) {
						#line 183 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
						int i2 = _g2++;
						#line 183 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
						((global::haxe.lang.Function) (oneTimersToRun[i2]) ).__hx_invoke0_o();
						#line 183 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
						oneTimersToRun[i2] = null;
					}
					
					#line 183 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
					if (this.isMainThread) {
						#line 183 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
						double next = global::haxe.MainLoop.tick();
						#line 183 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
						if (global::haxe.MainLoop.hasEvents()) {
							#line 183 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
							 ++ eventsToRunIdx;
							#line 183 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
							if (( nextEventAt > next )) {
								#line 264 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
								nextEventAt = next;
							}
							
						}
						
					}
					
					#line 183 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
					if (( eventsToRunIdx > 0 )) {
						#line 270 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
						nextEventAt = ((double) (-2) );
					}
					
					#line 183 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
					double r_nextEventAt = nextEventAt;
					#line 183 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
					bool r_anyTime = hasPromisedEvents;
					{
						#line 184 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
						bool _g4 = r_anyTime;
						#line 184 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
						double _g5 = r_nextEventAt;
						#line 184 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
						{
							#line 184 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
							double __temp_switch1 = (_g5);
							if (( __temp_switch1 == -2 )) {
							}
							else if (( __temp_switch1 == -1 )) {
								#line 184 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
								if (_g4) {
									#line 189 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
									this.waitLock.wait(default(global::haxe.lang.Null<double>));
								}
								else {
									#line 187 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
									goto label1;
								}
								
							}
							else {
								#line 190 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
								double time = _g5;
								#line 190 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
								{
									#line 191 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
									double timeout = ( time - global::Sys.time() );
									this.waitLock.wait(new global::haxe.lang.Null<double>(global::System.Math.Max(((double) (0) ), ((double) (timeout) )), true));
								}
								
							}
							
						}
						
					}
					
				}
				label1: {};
			}
			#line default
		}
		
		
		public override double __hx_setField_f(string field, int hash, double @value, bool handleProperties) {
			unchecked {
				#line 24 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
				switch (hash) {
					case 465747725:
					{
						#line 24 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
						this.promisedEventsCount = ((int) (@value) );
						#line 24 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
						return @value;
					}
					
					
					case 2036759185:
					{
						#line 24 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
						this.oneTimeEventsIdx = ((int) (@value) );
						#line 24 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
						return @value;
					}
					
					
					default:
					{
						#line 24 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
						return base.__hx_setField_f(field, hash, @value, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override object __hx_setField(string field, int hash, object @value, bool handleProperties) {
			unchecked {
				#line 24 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
				switch (hash) {
					case 914669677:
					{
						#line 24 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
						this.isMainThread = global::haxe.lang.Runtime.toBool(@value);
						#line 24 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
						return @value;
					}
					
					
					case 893862549:
					{
						#line 24 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
						this.regularEvents = ((global::sys.thread._EventLoop.RegularEvent) (@value) );
						#line 24 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
						return @value;
					}
					
					
					case 465747725:
					{
						#line 24 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
						this.promisedEventsCount = ((int) (global::haxe.lang.Runtime.toInt(@value)) );
						#line 24 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
						return @value;
					}
					
					
					case 1352270080:
					{
						#line 24 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
						this.waitLock = ((global::sys.thread.Lock) (@value) );
						#line 24 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
						return @value;
					}
					
					
					case 2036759185:
					{
						#line 24 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
						this.oneTimeEventsIdx = ((int) (global::haxe.lang.Runtime.toInt(@value)) );
						#line 24 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
						return @value;
					}
					
					
					case 22835468:
					{
						#line 24 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
						this.oneTimeEvents = ((global::Array<object>) (global::Array<object>.__hx_cast<object>(((global::Array) (@value) ))) );
						#line 24 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
						return @value;
					}
					
					
					case 274435967:
					{
						#line 24 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
						this.mutex = ((global::sys.thread.Mutex) (@value) );
						#line 24 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
						return @value;
					}
					
					
					default:
					{
						#line 24 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
						return base.__hx_setField(field, hash, @value, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override object __hx_getField(string field, int hash, bool throwErrors, bool isCheck, bool handleProperties) {
			unchecked {
				#line 24 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
				switch (hash) {
					case 1203218020:
					{
						#line 24 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "loop", 1203218020)) );
					}
					
					
					case 914669677:
					{
						#line 24 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
						return this.isMainThread;
					}
					
					
					case 893862549:
					{
						#line 24 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
						return this.regularEvents;
					}
					
					
					case 465747725:
					{
						#line 24 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
						return this.promisedEventsCount;
					}
					
					
					case 1352270080:
					{
						#line 24 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
						return this.waitLock;
					}
					
					
					case 2036759185:
					{
						#line 24 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
						return this.oneTimeEventsIdx;
					}
					
					
					case 22835468:
					{
						#line 24 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
						return this.oneTimeEvents;
					}
					
					
					case 274435967:
					{
						#line 24 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
						return this.mutex;
					}
					
					
					default:
					{
						#line 24 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
						return base.__hx_getField(field, hash, throwErrors, isCheck, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override double __hx_getField_f(string field, int hash, bool throwErrors, bool handleProperties) {
			unchecked {
				#line 24 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
				switch (hash) {
					case 465747725:
					{
						#line 24 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
						return ((double) (this.promisedEventsCount) );
					}
					
					
					case 2036759185:
					{
						#line 24 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
						return ((double) (this.oneTimeEventsIdx) );
					}
					
					
					default:
					{
						#line 24 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
						return base.__hx_getField_f(field, hash, throwErrors, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override object __hx_invokeField(string field, int hash, object[] dynargs) {
			unchecked {
				#line 24 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
				switch (hash) {
					case 1203218020:
					{
						#line 24 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
						this.loop();
						#line 24 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
						break;
					}
					
					
					default:
					{
						#line 24 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
						return base.__hx_invokeField(field, hash, dynargs);
					}
					
				}
				
				#line 24 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
				return null;
			}
			#line default
		}
		
		
		public override void __hx_getFields(global::Array<string> baseArr) {
			#line 24 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
			baseArr.push("isMainThread");
			#line 24 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
			baseArr.push("regularEvents");
			#line 24 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
			baseArr.push("promisedEventsCount");
			#line 24 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
			baseArr.push("waitLock");
			#line 24 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
			baseArr.push("oneTimeEventsIdx");
			#line 24 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
			baseArr.push("oneTimeEvents");
			#line 24 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
			baseArr.push("mutex");
			#line 24 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
			base.__hx_getFields(baseArr);
		}
		#line default
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace sys.thread._EventLoop {
	public class RegularEvent : global::haxe.lang.HxObject {
		
		public RegularEvent(global::haxe.lang.EmptyObject empty) {
		}
		
		
		public RegularEvent(global::haxe.lang.Function run, double nextRunTime, double interval) {
			#line 286 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
			global::sys.thread._EventLoop.RegularEvent.__hx_ctor_sys_thread__EventLoop_RegularEvent(this, run, nextRunTime, interval);
		}
		#line default
		
		protected static void __hx_ctor_sys_thread__EventLoop_RegularEvent(global::sys.thread._EventLoop.RegularEvent __hx_this, global::haxe.lang.Function run, double nextRunTime, double interval) {
			#line 284 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
			__hx_this.cancelled = false;
			#line 286 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
			{
				#line 287 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
				__hx_this.run = run;
				__hx_this.nextRunTime = nextRunTime;
				#line 289 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
				__hx_this.interval = interval;
			}
			
		}
		#line default
		
		public double nextRunTime;
		
		public double interval;
		
		public global::haxe.lang.Function run;
		
		public global::sys.thread._EventLoop.RegularEvent next;
		
		public bool cancelled;
		
		public override double __hx_setField_f(string field, int hash, double @value, bool handleProperties) {
			unchecked {
				#line 278 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
				switch (hash) {
					case 679246149:
					{
						#line 278 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
						this.interval = ((double) (@value) );
						#line 278 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
						return @value;
					}
					
					
					case 813914181:
					{
						#line 278 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
						this.nextRunTime = ((double) (@value) );
						#line 278 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
						return @value;
					}
					
					
					default:
					{
						#line 278 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
						return base.__hx_setField_f(field, hash, @value, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override object __hx_setField(string field, int hash, object @value, bool handleProperties) {
			unchecked {
				#line 278 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
				switch (hash) {
					case 573867665:
					{
						#line 278 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
						this.cancelled = global::haxe.lang.Runtime.toBool(@value);
						#line 278 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
						return @value;
					}
					
					
					case 1224901875:
					{
						#line 278 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
						this.next = ((global::sys.thread._EventLoop.RegularEvent) (@value) );
						#line 278 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
						return @value;
					}
					
					
					case 5695307:
					{
						#line 278 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
						this.run = ((global::haxe.lang.Function) (@value) );
						#line 278 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
						return @value;
					}
					
					
					case 679246149:
					{
						#line 278 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
						this.interval = ((double) (global::haxe.lang.Runtime.toDouble(@value)) );
						#line 278 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
						return @value;
					}
					
					
					case 813914181:
					{
						#line 278 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
						this.nextRunTime = ((double) (global::haxe.lang.Runtime.toDouble(@value)) );
						#line 278 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
						return @value;
					}
					
					
					default:
					{
						#line 278 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
						return base.__hx_setField(field, hash, @value, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override object __hx_getField(string field, int hash, bool throwErrors, bool isCheck, bool handleProperties) {
			unchecked {
				#line 278 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
				switch (hash) {
					case 573867665:
					{
						#line 278 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
						return this.cancelled;
					}
					
					
					case 1224901875:
					{
						#line 278 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
						return this.next;
					}
					
					
					case 5695307:
					{
						#line 278 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
						return this.run;
					}
					
					
					case 679246149:
					{
						#line 278 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
						return this.interval;
					}
					
					
					case 813914181:
					{
						#line 278 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
						return this.nextRunTime;
					}
					
					
					default:
					{
						#line 278 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
						return base.__hx_getField(field, hash, throwErrors, isCheck, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override double __hx_getField_f(string field, int hash, bool throwErrors, bool handleProperties) {
			unchecked {
				#line 278 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
				switch (hash) {
					case 679246149:
					{
						#line 278 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
						return this.interval;
					}
					
					
					case 813914181:
					{
						#line 278 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
						return this.nextRunTime;
					}
					
					
					default:
					{
						#line 278 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
						return base.__hx_getField_f(field, hash, throwErrors, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override void __hx_getFields(global::Array<string> baseArr) {
			#line 278 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
			baseArr.push("cancelled");
			#line 278 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
			baseArr.push("next");
			#line 278 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
			baseArr.push("run");
			#line 278 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
			baseArr.push("interval");
			#line 278 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
			baseArr.push("nextRunTime");
			#line 278 "D:\\Users\\pedro.cardoso\\stupidspeed\\tools\\haxe\\std\\sys\\thread\\EventLoop.hx"
			base.__hx_getFields(baseArr);
		}
		#line default
		
	}
}


