// Generated by Haxe 4.3.7

#pragma warning disable 109, 114, 219, 429, 168, 162
public class AddOne : global::haxe.lang.HxObject {
	
	public AddOne(global::haxe.lang.EmptyObject empty) {
	}
	
	
	public AddOne() {
		#line 7 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T03_func_sum\\AddOne.hx"
		global::AddOne.__hx_ctor__AddOne(this);
	}
	#line default
	
	protected static void __hx_ctor__AddOne(global::AddOne __hx_this) {
	}
	
	
	public static int add_one(int n) {
		unchecked {
			#line 9 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T03_func_sum\\AddOne.hx"
			return ( n + 1 );
		}
		#line default
	}
	
	
}


