// Generated by Haxe 4.3.7

#pragma warning disable 109, 114, 219, 429, 168, 162
public class T03_func_sum : global::haxe.lang.HxObject {
	
	public static void Main(){
		global::cs.Boot.init();
		{
			global::T03_func_sum.main();
			global::sys.thread._Thread.Thread_Impl_.processEvents();
		}
		;
	}
	public T03_func_sum(global::haxe.lang.EmptyObject empty) {
	}
	
	
	public T03_func_sum() {
		#line 12 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T03_func_sum\\T03_func_sum.hx"
		global::T03_func_sum.__hx_ctor__T03_func_sum(this);
	}
	#line default
	
	protected static void __hx_ctor__T03_func_sum(global::T03_func_sum __hx_this) {
	}
	
	
	public static void main() {
		unchecked {
			#line 15 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T03_func_sum\\T03_func_sum.hx"
			double t0 = global::Sys.time();
			int @value = 0;
			#line 18 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T03_func_sum\\T03_func_sum.hx"
			{
				#line 18 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T03_func_sum\\T03_func_sum.hx"
				int _g = 0;
				#line 18 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T03_func_sum\\T03_func_sum.hx"
				while (( _g < 100000000 )) {
					#line 18 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T03_func_sum\\T03_func_sum.hx"
					int i = _g++;
					@value = global::AddOne.add_one(@value);
				}
				
			}
			
			#line 22 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T03_func_sum\\T03_func_sum.hx"
			double t1 = global::Sys.time();
			global::Out.err(global::haxe.lang.Runtime.concat(global::haxe.lang.Runtime.concat("TIME_MS=", global::haxe.lang.Runtime.toString(( (( t1 - t0 )) * 1000.0 ))), "\n"));
			#line 24 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T03_func_sum\\T03_func_sum.hx"
			global::Out.line(@value);
		}
		#line default
	}
	
	
}


