
#ifndef _C1_co19_
#define _C1_co19_

#ifdef __cplusplus
extern "C" {
#endif

RTOSHF (EIF_REFERENCE,544)
static EIF_REFERENCE F32_544_body(EIF_REFERENCE);
extern EIF_REFERENCE F32_544(EIF_REFERENCE);
RTOSHF (EIF_REFERENCE,545)
static EIF_REFERENCE F32_545_body(EIF_REFERENCE);
extern EIF_REFERENCE F32_545(EIF_REFERENCE);
RTOSHF (EIF_REFERENCE,546)
static EIF_REFERENCE F32_546_body(EIF_REFERENCE);
extern EIF_REFERENCE F32_546(EIF_REFERENCE);
RTOSHF (EIF_REFERENCE,547)
static EIF_REFERENCE F32_547_body(EIF_REFERENCE);
extern EIF_REFERENCE F32_547(EIF_REFERENCE);
extern void EIF_Minit19(void);
extern EIF_REFERENCE F2_37(EIF_REFERENCE);
extern void F633_3037(EIF_REFERENCE, EIF_INTEGER_32);
extern EIF_REFERENCE F819_5046(EIF_REFERENCE);
extern EIF_REFERENCE F2_41(EIF_REFERENCE);
extern EIF_REFERENCE F2_36(EIF_REFERENCE);
extern EIF_REFERENCE F2_39(EIF_REFERENCE);
extern EIF_REFERENCE F2_40(EIF_REFERENCE);
extern EIF_REFERENCE F2_35(EIF_REFERENCE);
extern EIF_REFERENCE F2_38(EIF_REFERENCE);
extern EIF_REFERENCE F2_42(EIF_REFERENCE);
extern void F629_2971(EIF_REFERENCE, EIF_REFERENCE, EIF_REFERENCE);
RTOSHF(EIF_REFERENCE,35)
RTOSHF(EIF_REFERENCE,36)
RTOSHF(EIF_REFERENCE,37)
RTOSHF(EIF_REFERENCE,39)
RTOSHF(EIF_REFERENCE,38)
RTOSHF(EIF_REFERENCE,40)
RTOSHF(EIF_REFERENCE,41)
RTOSHF(EIF_REFERENCE,42)

#ifdef __cplusplus
}
#endif

#endif
