
#ifndef _C1_en4_
#define _C1_en4_

#ifdef __cplusplus
extern "C" {
#endif

extern void F4_50(EIF_REFERENCE, EIF_REFERENCE);
extern EIF_REFERENCE F4_52(EIF_REFERENCE);
extern EIF_REFERENCE F4_53(EIF_REFERENCE);
extern void F4_56(EIF_REFERENCE, EIF_REFERENCE, EIF_REFERENCE);
extern EIF_BOOLEAN F4_57(EIF_REFERENCE);
extern EIF_BOOLEAN F4_59(EIF_REFERENCE, EIF_REFERENCE);
extern EIF_BOOLEAN F4_60(EIF_REFERENCE);
extern EIF_BOOLEAN F4_61(EIF_REFERENCE, EIF_REFERENCE);
RTOSHF (EIF_REFERENCE,63)
static EIF_REFERENCE F4_63_body(EIF_REFERENCE);
extern EIF_REFERENCE F4_63(EIF_REFERENCE);
RTOSHF (EIF_REFERENCE,64)
static EIF_REFERENCE F4_64_body(EIF_REFERENCE);
extern EIF_REFERENCE F4_64(EIF_REFERENCE);
extern void EIF_Minit4(void);
extern EIF_BOOLEAN F817_4924(EIF_REFERENCE, EIF_REFERENCE);
extern EIF_REFERENCE F821_5128(EIF_REFERENCE);
extern void F821_5127(EIF_REFERENCE);
extern char *(*R3748[])();
extern char *(*R3753[])();
extern char *(*R3755[])();

#ifdef __cplusplus
}
#endif

#endif
