// Generated by Haxe 4.3.7

#pragma warning disable 109, 114, 219, 429, 168, 162
public class T07_string_append : global::haxe.lang.HxObject {
	
	public static void Main(){
		global::cs.Boot.init();
		{
			global::T07_string_append.main();
			global::sys.thread._Thread.Thread_Impl_.processEvents();
		}
		;
	}
	public T07_string_append(global::haxe.lang.EmptyObject empty) {
	}
	
	
	public T07_string_append() {
		#line 12 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T07_string_append\\T07_string_append.hx"
		global::T07_string_append.__hx_ctor__T07_string_append(this);
	}
	#line default
	
	protected static void __hx_ctor__T07_string_append(global::T07_string_append __hx_this) {
	}
	
	
	public static void main() {
		unchecked {
			#line 15 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T07_string_append\\T07_string_append.hx"
			double t0 = global::Sys.time();
			string text = "";
			#line 18 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T07_string_append\\T07_string_append.hx"
			{
				#line 18 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T07_string_append\\T07_string_append.hx"
				int _g = 0;
				#line 18 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T07_string_append\\T07_string_append.hx"
				while (( _g < 250000 )) {
					#line 18 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T07_string_append\\T07_string_append.hx"
					int i = _g++;
					text = global::haxe.lang.Runtime.concat(text, "x");
				}
				
			}
			
			#line 22 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T07_string_append\\T07_string_append.hx"
			double t1 = global::Sys.time();
			global::Out.err(global::haxe.lang.Runtime.concat(global::haxe.lang.Runtime.concat("TIME_MS=", global::haxe.lang.Runtime.toString(( (( t1 - t0 )) * 1000.0 ))), "\n"));
			#line 24 "D:\\Users\\pedro.cardoso\\stupidspeed\\exec\\haxe\\T07_string_append\\T07_string_append.hx"
			global::Out.line(text.Length);
		}
		#line default
	}
	
	
}


