// Generated by Haxe 4.3.7

#pragma warning disable 109, 114, 219, 429, 168, 162
public class Math {
	
	public Math() {
	}
	
	
	public static readonly double NEGATIVE_INFINITY = global::System.Double.NegativeInfinity;
	
}


